// Comprehensive Effects Library with 100+ effects organized by category

export type PerformanceLevel = 'Light' | 'Medium' | 'Heavy'

export type GenreTag = 
  | 'Fantasy' 
  | 'Horror' 
  | 'Sci-Fi' 
  | 'Cyberpunk' 
  | 'Steampunk' 
  | 'Wasteland' 
  | 'Nature' 
  | 'City'

export type EffectTypeTag = 
  | 'Weather' 
  | 'Fire' 
  | 'Water' 
  | 'Magic' 
  | 'Light' 
  | 'Creature' 
  | 'Environmental' 
  | 'Set Piece'

export type EffectCategory =
  | 'weather-atmosphere'
  | 'water-effects'
  | 'fire-heat'
  | 'light-sources'
  | 'fantasy-magic'
  | 'life-nature'
  | 'city-settlement'
  | 'horror-dark'
  | 'sci-fi'
  | 'cyberpunk'
  | 'steampunk'
  | 'wasteland'
  | 'set-pieces'

export type BaseEffectComponent =
  | 'ParticleField'
  | 'GlowPulse'
  | 'WaveFlow'
  | 'SmokeFog'
  | 'Lightning'
  | 'BeamSweep'
  | 'Glitch'
  | 'SwarmMovement'
  | 'ShadowCreep'
  | 'MechanicalMotion'
  | 'SetPieceShake'
  | 'FlameFlicker'
  | 'RippleWave'
  | 'RotatingRunes'
  | 'Portal'

export interface UnifiedEffectSettings {
  speed: number
  intensity: number
  density: number
  opacity: number
  glow: number
  colorA: string
  colorB: string
  angle: number
  turbulence: number
  scale: number
  pulseRate: number
  flicker: number
}

export interface ExpandedEffectDefinition {
  id: string
  name: string
  category: EffectCategory
  genreTags: GenreTag[]
  effectTags: EffectTypeTag[]
  description: string
  performance: PerformanceLevel
  defaultSettings: Partial<UnifiedEffectSettings>
  baseComponent: BaseEffectComponent
  defaultSize: { width: number; height: number }
}

// Category metadata for the browser
export const categoryMeta: Record<EffectCategory, { name: string; icon: string; description: string }> = {
  'weather-atmosphere': { name: 'Weather & Atmosphere', icon: 'cloud', description: 'Rain, snow, fog, and atmospheric effects' },
  'water-effects': { name: 'Water Effects', icon: 'droplet', description: 'Rivers, waves, ripples, and liquid animations' },
  'fire-heat': { name: 'Fire & Heat', icon: 'flame', description: 'Flames, lava, torches, and heat effects' },
  'light-sources': { name: 'Light Sources', icon: 'sun', description: 'Sunbeams, lanterns, and light effects' },
  'fantasy-magic': { name: 'Fantasy Magic', icon: 'sparkles', description: 'Portals, runes, spells, and arcane effects' },
  'life-nature': { name: 'Life & Nature', icon: 'leaf', description: 'Creatures, insects, and natural movement' },
  'city-settlement': { name: 'City & Settlement', icon: 'building', description: 'Urban animations and settlement effects' },
  'horror-dark': { name: 'Horror & Dark Fantasy', icon: 'skull', description: 'Shadows, ghosts, and creepy effects' },
  'sci-fi': { name: 'Sci-Fi', icon: 'rocket', description: 'Holograms, shields, and futuristic effects' },
  'cyberpunk': { name: 'Cyberpunk', icon: 'cpu', description: 'Neon, glitches, and digital effects' },
  'steampunk': { name: 'Steampunk', icon: 'cog', description: 'Gears, steam, and mechanical effects' },
  'wasteland': { name: 'Wasteland / Post-Apocalypse', icon: 'radiation', description: 'Radiation, decay, and survival effects' },
  'set-pieces': { name: 'Large Set-Piece Effects', icon: 'mountain', description: 'Earthquakes, eruptions, and epic events' },
}

// Full effects library
export const effectsLibrary: ExpandedEffectDefinition[] = [
  // ========== WEATHER & ATMOSPHERE ==========
  {
    id: 'falling-rain',
    name: 'Falling Rain',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Horror', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Gentle diagonal rain streaks',
    performance: 'Light',
    defaultSettings: { speed: 0.6, intensity: 0.5, angle: 15, colorA: '#7ca8d9' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'heavy-thunderstorm',
    name: 'Heavy Thunderstorm',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Horror', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Intense rain with flash lighting',
    performance: 'Heavy',
    defaultSettings: { speed: 0.9, intensity: 0.9, angle: 20, flicker: 0.8, colorA: '#5a8cbf' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 500, height: 500 },
  },
  {
    id: 'lightning-strikes',
    name: 'Lightning Strikes',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Horror', 'Nature'],
    effectTags: ['Weather', 'Light'],
    description: 'Dramatic lightning bolts',
    performance: 'Medium',
    defaultSettings: { intensity: 0.7, flicker: 0.9, colorA: '#ffffff', colorB: '#b3d4fc' },
    baseComponent: 'Lightning',
    defaultSize: { width: 300, height: 400 },
  },
  {
    id: 'drifting-fog',
    name: 'Drifting Fog',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Horror', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Semi-transparent rolling fog layer',
    performance: 'Light',
    defaultSettings: { speed: 0.3, density: 0.6, colorA: '#c4cdd4' },
    baseComponent: 'SmokeFog',
    defaultSize: { width: 600, height: 300 },
  },
  {
    id: 'dense-ground-mist',
    name: 'Dense Ground Mist',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Horror', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Low-lying thick mist',
    performance: 'Medium',
    defaultSettings: { speed: 0.2, density: 0.8, colorA: '#d8dfe6' },
    baseComponent: 'SmokeFog',
    defaultSize: { width: 500, height: 200 },
  },
  {
    id: 'snowfall',
    name: 'Snowfall',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Gentle drifting snow particles',
    performance: 'Light',
    defaultSettings: { speed: 0.3, density: 0.5, scale: 0.5, colorA: '#ffffff' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'blizzard-winds',
    name: 'Blizzard Winds',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Harsh wind-driven snow',
    performance: 'Heavy',
    defaultSettings: { speed: 0.9, density: 0.9, angle: 45, turbulence: 0.8, colorA: '#f0f5ff' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 500, height: 400 },
  },
  {
    id: 'sandstorm',
    name: 'Sandstorm',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Wasteland'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Swirling desert sand',
    performance: 'Heavy',
    defaultSettings: { speed: 0.8, density: 0.7, angle: 30, colorA: '#d4a574', colorB: '#8b6914' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 500, height: 400 },
  },
  {
    id: 'ash-fall',
    name: 'Ash Fall',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Wasteland', 'Horror'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Falling volcanic ash or debris',
    performance: 'Light',
    defaultSettings: { speed: 0.4, density: 0.5, colorA: '#4a4a4a', colorB: '#2d2d2d' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'floating-pollen',
    name: 'Floating Pollen',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Gentle floating pollen or seeds',
    performance: 'Light',
    defaultSettings: { speed: 0.2, density: 0.4, colorA: '#f5e6a3', glow: 0.3 },
    baseComponent: 'ParticleField',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'autumn-leaves',
    name: 'Autumn Leaves Blowing',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Colorful falling leaves',
    performance: 'Medium',
    defaultSettings: { speed: 0.4, density: 0.3, turbulence: 0.6, colorA: '#d4763a', colorB: '#8b4513' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'dust-motes',
    name: 'Dust Motes in Sunlight',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Environmental', 'Light'],
    description: 'Floating atmospheric particles',
    performance: 'Light',
    defaultSettings: { speed: 0.15, density: 0.4, colorA: '#fff8dc', glow: 0.4 },
    baseComponent: 'ParticleField',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'heat-haze',
    name: 'Heat Haze Distortion',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Wasteland'],
    effectTags: ['Environmental'],
    description: 'Shimmering heat distortion',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, intensity: 0.5, turbulence: 0.7 },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 400, height: 200 },
  },
  {
    id: 'wind-grass',
    name: 'Wind Gusts Moving Grass',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Grass swaying in the wind',
    performance: 'Light',
    defaultSettings: { speed: 0.4, intensity: 0.5, angle: 15, colorA: '#6b8e23' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 400, height: 150 },
  },
  {
    id: 'tornado-distance',
    name: 'Tornado in Distance',
    category: 'weather-atmosphere',
    genreTags: ['Fantasy', 'Wasteland', 'Nature'],
    effectTags: ['Weather', 'Set Piece'],
    description: 'Distant rotating funnel cloud',
    performance: 'Heavy',
    defaultSettings: { speed: 0.7, intensity: 0.8, turbulence: 0.9, colorA: '#5a5a5a' },
    baseComponent: 'Portal',
    defaultSize: { width: 150, height: 300 },
  },

  // ========== WATER EFFECTS ==========
  {
    id: 'ocean-waves',
    name: 'Ocean Waves',
    category: 'water-effects',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Water', 'Environmental'],
    description: 'Rolling ocean wave patterns',
    performance: 'Medium',
    defaultSettings: { speed: 0.4, scale: 0.7, colorA: '#1e5f8a', colorB: '#3498db' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 500, height: 300 },
  },
  {
    id: 'river-flow',
    name: 'River Flow',
    category: 'water-effects',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Water', 'Environmental'],
    description: 'Flowing river current',
    performance: 'Light',
    defaultSettings: { speed: 0.5, intensity: 0.6, angle: 0, colorA: '#4a90d9' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 400, height: 150 },
  },
  {
    id: 'waterfalls',
    name: 'Waterfalls',
    category: 'water-effects',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Water', 'Environmental'],
    description: 'Cascading waterfall spray',
    performance: 'Medium',
    defaultSettings: { speed: 0.8, intensity: 0.7, density: 0.6, colorA: '#87ceeb', colorB: '#ffffff' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 200, height: 350 },
  },
  {
    id: 'pond-ripples',
    name: 'Pond Ripples',
    category: 'water-effects',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Water', 'Environmental'],
    description: 'Expanding circular ripples',
    performance: 'Light',
    defaultSettings: { speed: 0.4, scale: 0.5, colorA: '#5dade2' },
    baseComponent: 'RippleWave',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'raindrop-splashes',
    name: 'Raindrop Splashes',
    category: 'water-effects',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Water', 'Weather'],
    description: 'Rain impacts on surfaces',
    performance: 'Medium',
    defaultSettings: { speed: 0.6, density: 0.5, colorA: '#87ceeb' },
    baseComponent: 'RippleWave',
    defaultSize: { width: 400, height: 200 },
  },
  {
    id: 'sewer-water',
    name: 'Sewer Water Movement',
    category: 'water-effects',
    genreTags: ['Fantasy', 'Horror', 'City'],
    effectTags: ['Water', 'Environmental'],
    description: 'Murky flowing sewer water',
    performance: 'Light',
    defaultSettings: { speed: 0.3, intensity: 0.4, colorA: '#4a5c3e', colorB: '#2d3b24' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 400, height: 150 },
  },
  {
    id: 'swamp-bubbles',
    name: 'Swamp Bubbles',
    category: 'water-effects',
    genreTags: ['Fantasy', 'Horror', 'Nature'],
    effectTags: ['Water', 'Environmental'],
    description: 'Rising gas bubbles',
    performance: 'Light',
    defaultSettings: { speed: 0.3, density: 0.4, colorA: '#556b2f' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'bioluminescent-water',
    name: 'Bioluminescent Water',
    category: 'water-effects',
    genreTags: ['Fantasy', 'Sci-Fi'],
    effectTags: ['Water', 'Magic', 'Light'],
    description: 'Glowing water organisms',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, glow: 0.8, density: 0.5, colorA: '#00ffff', colorB: '#7fff00' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 400, height: 300 },
  },
  {
    id: 'blood-river',
    name: 'Blood-Red River Flow',
    category: 'water-effects',
    genreTags: ['Horror', 'Fantasy'],
    effectTags: ['Water', 'Environmental'],
    description: 'Dark red flowing liquid',
    performance: 'Light',
    defaultSettings: { speed: 0.4, intensity: 0.5, colorA: '#8b0000', colorB: '#4a0000' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 400, height: 150 },
  },
  {
    id: 'toxic-waste',
    name: 'Toxic Waste Currents',
    category: 'water-effects',
    genreTags: ['Sci-Fi', 'Wasteland', 'Cyberpunk'],
    effectTags: ['Water', 'Environmental'],
    description: 'Glowing toxic liquid flow',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, glow: 0.7, colorA: '#39ff14', colorB: '#00ff00' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 400, height: 150 },
  },

  // ========== FIRE & HEAT ==========
  {
    id: 'campfire',
    name: 'Campfires',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Fire', 'Light'],
    description: 'Flickering campfire with embers',
    performance: 'Medium',
    defaultSettings: { speed: 0.6, intensity: 0.7, flicker: 0.6, colorA: '#ff6600', colorB: '#ffcc00' },
    baseComponent: 'FlameFlicker',
    defaultSize: { width: 200, height: 250 },
  },
  {
    id: 'fireplace',
    name: 'Fireplace Flames',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'City'],
    effectTags: ['Fire', 'Light'],
    description: 'Cozy hearth fire',
    performance: 'Medium',
    defaultSettings: { speed: 0.5, intensity: 0.6, flicker: 0.5, colorA: '#ff4500', colorB: '#ffa500' },
    baseComponent: 'FlameFlicker',
    defaultSize: { width: 250, height: 200 },
  },
  {
    id: 'torch-flicker',
    name: 'Torch Flicker',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Fire', 'Light'],
    description: 'Wall-mounted torch flame',
    performance: 'Light',
    defaultSettings: { speed: 0.7, flicker: 0.7, glow: 0.6, colorA: '#ff9933' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 150, height: 200 },
  },
  {
    id: 'lava-flow',
    name: 'Lava Flow',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'Wasteland'],
    effectTags: ['Fire', 'Environmental'],
    description: 'Flowing molten lava',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, intensity: 0.8, glow: 0.7, colorA: '#ff4400', colorB: '#ff6600' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 400, height: 200 },
  },
  {
    id: 'lava-bubbles',
    name: 'Lava Bubbles',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'Wasteland'],
    effectTags: ['Fire', 'Environmental'],
    description: 'Bubbling lava surface',
    performance: 'Medium',
    defaultSettings: { speed: 0.4, density: 0.5, glow: 0.6, colorA: '#ff3300', colorB: '#ff6600' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'burning-building',
    name: 'Burning Buildings',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'Horror', 'Wasteland'],
    effectTags: ['Fire', 'Set Piece'],
    description: 'Large structure fire',
    performance: 'Heavy',
    defaultSettings: { speed: 0.7, intensity: 0.9, density: 0.7, colorA: '#ff4500', colorB: '#ff8c00' },
    baseComponent: 'FlameFlicker',
    defaultSize: { width: 400, height: 500 },
  },
  {
    id: 'forest-fire',
    name: 'Forest Fire',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'Wasteland', 'Nature'],
    effectTags: ['Fire', 'Set Piece'],
    description: 'Spreading wildfire',
    performance: 'Heavy',
    defaultSettings: { speed: 0.8, intensity: 0.9, density: 0.8, colorA: '#ff4500', colorB: '#dc143c' },
    baseComponent: 'FlameFlicker',
    defaultSize: { width: 500, height: 400 },
  },
  {
    id: 'candle-flicker',
    name: 'Candle Flickering',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Fire', 'Light'],
    description: 'Small candle flame',
    performance: 'Light',
    defaultSettings: { speed: 0.5, flicker: 0.4, glow: 0.4, colorA: '#ffaa00' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 80, height: 120 },
  },
  {
    id: 'forge-fire',
    name: 'Forge Fires',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'Steampunk'],
    effectTags: ['Fire', 'Light'],
    description: 'Intense blacksmith forge',
    performance: 'Medium',
    defaultSettings: { speed: 0.6, intensity: 0.8, glow: 0.8, colorA: '#ff6600', colorB: '#ffffff' },
    baseComponent: 'FlameFlicker',
    defaultSize: { width: 250, height: 200 },
  },
  {
    id: 'molten-metal',
    name: 'Molten Metal Pours',
    category: 'fire-heat',
    genreTags: ['Fantasy', 'Steampunk'],
    effectTags: ['Fire', 'Environmental'],
    description: 'Glowing liquid metal',
    performance: 'Medium',
    defaultSettings: { speed: 0.5, glow: 0.9, colorA: '#ffcc00', colorB: '#ff6600' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 150, height: 300 },
  },

  // ========== LIGHT SOURCES ==========
  {
    id: 'sunbeams',
    name: 'Sunbeams Through Windows',
    category: 'light-sources',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Light', 'Environmental'],
    description: 'Streaming rays of sunlight',
    performance: 'Light',
    defaultSettings: { angle: 45, intensity: 0.6, glow: 0.5, colorA: '#fff8dc' },
    baseComponent: 'BeamSweep',
    defaultSize: { width: 300, height: 400 },
  },
  {
    id: 'moonlight-clouds',
    name: 'Moonlight Through Clouds',
    category: 'light-sources',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Light', 'Environmental'],
    description: 'Shifting moonlit clouds',
    performance: 'Light',
    defaultSettings: { speed: 0.2, intensity: 0.4, colorA: '#c4d4e8', colorB: '#8fa8c4' },
    baseComponent: 'SmokeFog',
    defaultSize: { width: 500, height: 300 },
  },
  {
    id: 'flickering-lantern',
    name: 'Flickering Lanterns',
    category: 'light-sources',
    genreTags: ['Fantasy', 'Horror', 'City'],
    effectTags: ['Light', 'Fire'],
    description: 'Hanging oil lantern glow',
    performance: 'Light',
    defaultSettings: { flicker: 0.5, glow: 0.6, colorA: '#ffcc66' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 150, height: 150 },
  },
  {
    id: 'stained-glass',
    name: 'Colored Stained-Glass Lighting',
    category: 'light-sources',
    genreTags: ['Fantasy'],
    effectTags: ['Light', 'Magic'],
    description: 'Colored light patterns',
    performance: 'Light',
    defaultSettings: { intensity: 0.5, colorA: '#ff6b6b', colorB: '#4ecdc4' },
    baseComponent: 'BeamSweep',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'lighthouse-beam',
    name: 'Rotating Lighthouse Beam',
    category: 'light-sources',
    genreTags: ['Fantasy', 'Horror', 'Nature'],
    effectTags: ['Light'],
    description: 'Sweeping searchlight',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, intensity: 0.8, angle: 0, colorA: '#fffacd' },
    baseComponent: 'BeamSweep',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'crystal-glow',
    name: 'Magical Crystal Glow',
    category: 'light-sources',
    genreTags: ['Fantasy'],
    effectTags: ['Light', 'Magic'],
    description: 'Pulsing crystal emanation',
    performance: 'Light',
    defaultSettings: { pulseRate: 0.4, glow: 0.8, colorA: '#00ffff', colorB: '#ff00ff' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 150, height: 150 },
  },
  {
    id: 'pulsing-runes',
    name: 'Pulsing Rune Circles',
    category: 'light-sources',
    genreTags: ['Fantasy'],
    effectTags: ['Light', 'Magic'],
    description: 'Glowing floor runes',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, glow: 0.7, pulseRate: 0.5, colorA: '#7c3aed' },
    baseComponent: 'RotatingRunes',
    defaultSize: { width: 200, height: 200 },
  },
  {
    id: 'will-o-wisps',
    name: 'Dancing Will-o-Wisps',
    category: 'light-sources',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Light', 'Magic', 'Creature'],
    description: 'Floating ghost lights',
    performance: 'Medium',
    defaultSettings: { speed: 0.4, glow: 0.8, density: 0.3, colorA: '#00ff88', colorB: '#88ffff' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'arcane-streetlamp',
    name: 'Arcane Street Lamps',
    category: 'light-sources',
    genreTags: ['Fantasy', 'City'],
    effectTags: ['Light', 'Magic'],
    description: 'Magical illumination post',
    performance: 'Light',
    defaultSettings: { glow: 0.6, pulseRate: 0.2, colorA: '#e6ccff' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 150, height: 200 },
  },
  {
    id: 'searchlights',
    name: 'Searchlights',
    category: 'light-sources',
    genreTags: ['Sci-Fi', 'City', 'Wasteland'],
    effectTags: ['Light'],
    description: 'Sweeping search beams',
    performance: 'Medium',
    defaultSettings: { speed: 0.4, intensity: 0.9, colorA: '#ffffff' },
    baseComponent: 'BeamSweep',
    defaultSize: { width: 400, height: 400 },
  },

  // ========== FANTASY MAGIC ==========
  {
    id: 'teleportation-circle',
    name: 'Teleportation Circles',
    category: 'fantasy-magic',
    genreTags: ['Fantasy'],
    effectTags: ['Magic', 'Light'],
    description: 'Arcane transport sigil',
    performance: 'Medium',
    defaultSettings: { speed: 0.4, glow: 0.9, pulseRate: 0.5, colorA: '#9966ff' },
    baseComponent: 'RotatingRunes',
    defaultSize: { width: 250, height: 250 },
  },
  {
    id: 'floating-sigils',
    name: 'Floating Arcane Sigils',
    category: 'fantasy-magic',
    genreTags: ['Fantasy'],
    effectTags: ['Magic', 'Light'],
    description: 'Hovering magical symbols',
    performance: 'Light',
    defaultSettings: { speed: 0.2, glow: 0.7, density: 0.3, colorA: '#7c3aed' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'magic-barrier',
    name: 'Magical Barrier Shimmer',
    category: 'fantasy-magic',
    genreTags: ['Fantasy', 'Sci-Fi'],
    effectTags: ['Magic', 'Light'],
    description: 'Protective force field',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, glow: 0.6, turbulence: 0.4, colorA: '#00ffff', colorB: '#ff00ff' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 300, height: 400 },
  },
  {
    id: 'mana-streams',
    name: 'Mana Streams',
    category: 'fantasy-magic',
    genreTags: ['Fantasy'],
    effectTags: ['Magic', 'Light'],
    description: 'Flowing magical energy',
    performance: 'Medium',
    defaultSettings: { speed: 0.5, glow: 0.8, colorA: '#00ccff', colorB: '#cc00ff' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 350, height: 150 },
  },
  {
    id: 'spell-particles',
    name: 'Floating Spell Particles',
    category: 'fantasy-magic',
    genreTags: ['Fantasy'],
    effectTags: ['Magic', 'Light'],
    description: 'Ambient magical particles',
    performance: 'Light',
    defaultSettings: { speed: 0.2, glow: 0.7, density: 0.4, colorA: '#ff88ff', colorB: '#88ffff' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'portal-vortex',
    name: 'Portal Vortex',
    category: 'fantasy-magic',
    genreTags: ['Fantasy', 'Sci-Fi'],
    effectTags: ['Magic', 'Light'],
    description: 'Swirling dimensional gate',
    performance: 'Heavy',
    defaultSettings: { speed: 0.5, glow: 0.9, turbulence: 0.7, colorA: '#9966ff', colorB: '#00ffff' },
    baseComponent: 'Portal',
    defaultSize: { width: 250, height: 250 },
  },
  {
    id: 'arcane-lightning',
    name: 'Arcane Lightning',
    category: 'fantasy-magic',
    genreTags: ['Fantasy'],
    effectTags: ['Magic', 'Light'],
    description: 'Magical electrical discharge',
    performance: 'Medium',
    defaultSettings: { speed: 0.7, flicker: 0.8, colorA: '#cc66ff', colorB: '#ffffff' },
    baseComponent: 'Lightning',
    defaultSize: { width: 200, height: 300 },
  },
  {
    id: 'summoning-circle',
    name: 'Summoning Circles',
    category: 'fantasy-magic',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Magic', 'Light'],
    description: 'Conjuration ritual sigil',
    performance: 'Heavy',
    defaultSettings: { speed: 0.3, glow: 0.9, pulseRate: 0.6, colorA: '#ff3333', colorB: '#990000' },
    baseComponent: 'RotatingRunes',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'floating-books',
    name: 'Floating Enchanted Books',
    category: 'fantasy-magic',
    genreTags: ['Fantasy'],
    effectTags: ['Magic'],
    description: 'Levitating magical tomes',
    performance: 'Medium',
    defaultSettings: { speed: 0.2, glow: 0.4, density: 0.2 },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'spirit-apparitions',
    name: 'Spirit Apparitions',
    category: 'fantasy-magic',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Magic', 'Creature'],
    description: 'Ghostly spirit forms',
    performance: 'Medium',
    defaultSettings: { speed: 0.2, opacity: 0.5, glow: 0.6, colorA: '#88ccff' },
    baseComponent: 'ShadowCreep',
    defaultSize: { width: 200, height: 300 },
  },
  {
    id: 'fairy-dust',
    name: 'Fairy Dust Trails',
    category: 'fantasy-magic',
    genreTags: ['Fantasy'],
    effectTags: ['Magic', 'Creature', 'Light'],
    description: 'Sparkling magical trails',
    performance: 'Light',
    defaultSettings: { speed: 0.4, glow: 0.9, density: 0.5, colorA: '#ffcc00', colorB: '#ff66cc' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'living-shadows',
    name: 'Living Shadows',
    category: 'fantasy-magic',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Magic', 'Creature'],
    description: 'Animated dark shapes',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, opacity: 0.7, colorA: '#1a1a2e' },
    baseComponent: 'ShadowCreep',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'holy-radiance',
    name: 'Divine Holy Radiance',
    category: 'fantasy-magic',
    genreTags: ['Fantasy'],
    effectTags: ['Magic', 'Light'],
    description: 'Blessed golden light',
    performance: 'Medium',
    defaultSettings: { intensity: 0.8, glow: 0.9, pulseRate: 0.3, colorA: '#fffacd', colorB: '#ffd700' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'necrotic-corruption',
    name: 'Necrotic Corruption Spreading',
    category: 'fantasy-magic',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Magic', 'Environmental'],
    description: 'Dark decay spreading',
    performance: 'Heavy',
    defaultSettings: { speed: 0.2, intensity: 0.7, colorA: '#2d1b4e', colorB: '#1a0a2e' },
    baseComponent: 'ShadowCreep',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'magical-eyes',
    name: 'Floating Magical Eyes',
    category: 'fantasy-magic',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Magic', 'Creature'],
    description: 'Watching arcane orbs',
    performance: 'Medium',
    defaultSettings: { speed: 0.2, glow: 0.7, density: 0.2, colorA: '#ff6600', colorB: '#ffcc00' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 300, height: 300 },
  },

  // ========== LIFE & NATURE ==========
  {
    id: 'birds-overhead',
    name: 'Birds Flying Overhead',
    category: 'life-nature',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Creature', 'Environmental'],
    description: 'Distant flying birds',
    performance: 'Light',
    defaultSettings: { speed: 0.4, density: 0.3, colorA: '#2d2d2d' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 400, height: 200 },
  },
  {
    id: 'bat-flock',
    name: 'Flocks of Bats',
    category: 'life-nature',
    genreTags: ['Fantasy', 'Horror'],
    effectTags: ['Creature', 'Environmental'],
    description: 'Swarming bats',
    performance: 'Medium',
    defaultSettings: { speed: 0.6, density: 0.5, colorA: '#1a1a1a' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 400, height: 300 },
  },
  {
    id: 'fireflies',
    name: 'Fireflies',
    category: 'life-nature',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Creature', 'Light'],
    description: 'Blinking light bugs',
    performance: 'Light',
    defaultSettings: { speed: 0.2, glow: 0.8, density: 0.4, flicker: 0.5, colorA: '#ccff00' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 400, height: 300 },
  },
  {
    id: 'butterflies',
    name: 'Butterflies',
    category: 'life-nature',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Creature', 'Environmental'],
    description: 'Fluttering butterflies',
    performance: 'Light',
    defaultSettings: { speed: 0.3, density: 0.3, colorA: '#ff88cc', colorB: '#88ccff' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'fish-schools',
    name: 'Fish Schools',
    category: 'life-nature',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Creature', 'Water'],
    description: 'Schooling fish movement',
    performance: 'Medium',
    defaultSettings: { speed: 0.4, density: 0.5, colorA: '#c0c0c0', colorB: '#87ceeb' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 400, height: 250 },
  },
  {
    id: 'rats-scurrying',
    name: 'Rats Scurrying',
    category: 'life-nature',
    genreTags: ['Fantasy', 'Horror', 'City'],
    effectTags: ['Creature', 'Environmental'],
    description: 'Small rodent movement',
    performance: 'Light',
    defaultSettings: { speed: 0.6, density: 0.3, colorA: '#4a3c31' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 300, height: 150 },
  },
  {
    id: 'crawling-insects',
    name: 'Crawling Insects',
    category: 'life-nature',
    genreTags: ['Fantasy', 'Horror', 'Nature'],
    effectTags: ['Creature', 'Environmental'],
    description: 'Surface-crawling bugs',
    performance: 'Light',
    defaultSettings: { speed: 0.4, density: 0.4, colorA: '#2d2d2d' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 300, height: 200 },
  },
  {
    id: 'floating-jellyfish',
    name: 'Floating Jellyfish Creatures',
    category: 'life-nature',
    genreTags: ['Fantasy', 'Sci-Fi'],
    effectTags: ['Creature', 'Magic'],
    description: 'Ethereal floating organisms',
    performance: 'Medium',
    defaultSettings: { speed: 0.2, glow: 0.6, density: 0.2, colorA: '#ff88ff', colorB: '#88ffff' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'grazing-animals',
    name: 'Grazing Animals',
    category: 'life-nature',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Creature', 'Environmental'],
    description: 'Distant herd movement',
    performance: 'Light',
    defaultSettings: { speed: 0.1, density: 0.2, colorA: '#8b7355' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 400, height: 200 },
  },
  {
    id: 'flying-dragons',
    name: 'Flying Dragons in Distance',
    category: 'life-nature',
    genreTags: ['Fantasy'],
    effectTags: ['Creature', 'Set Piece'],
    description: 'Distant dragon silhouettes',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, scale: 0.8, colorA: '#2d2d2d' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 500, height: 300 },
  },

  // ========== CITY & SETTLEMENT ==========
  {
    id: 'chimney-smoke',
    name: 'Chimney Smoke',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'City', 'Steampunk'],
    effectTags: ['Environmental'],
    description: 'Rising chimney smoke',
    performance: 'Light',
    defaultSettings: { speed: 0.3, density: 0.5, colorA: '#696969', colorB: '#a9a9a9' },
    baseComponent: 'SmokeFog',
    defaultSize: { width: 150, height: 300 },
  },
  {
    id: 'market-banners',
    name: 'Market Banners Waving',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'City'],
    effectTags: ['Environmental'],
    description: 'Cloth banners in wind',
    performance: 'Light',
    defaultSettings: { speed: 0.4, turbulence: 0.5, colorA: '#cc3333', colorB: '#336699' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 200, height: 150 },
  },
  {
    id: 'tavern-sign',
    name: 'Tavern Signs Swinging',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'City'],
    effectTags: ['Environmental'],
    description: 'Creaking hanging sign',
    performance: 'Light',
    defaultSettings: { speed: 0.3, angle: 15 },
    baseComponent: 'MechanicalMotion',
    defaultSize: { width: 150, height: 100 },
  },
  {
    id: 'windmill',
    name: 'Windmills Turning',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Environmental'],
    description: 'Rotating windmill blades',
    performance: 'Light',
    defaultSettings: { speed: 0.3 },
    baseComponent: 'MechanicalMotion',
    defaultSize: { width: 200, height: 200 },
  },
  {
    id: 'waterwheel',
    name: 'Waterwheels Spinning',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'City'],
    effectTags: ['Water', 'Environmental'],
    description: 'Rotating water wheel',
    performance: 'Light',
    defaultSettings: { speed: 0.4 },
    baseComponent: 'MechanicalMotion',
    defaultSize: { width: 200, height: 200 },
  },
  {
    id: 'laundry-flapping',
    name: 'Laundry Flapping',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'City'],
    effectTags: ['Environmental'],
    description: 'Clothes on a line',
    performance: 'Light',
    defaultSettings: { speed: 0.4, turbulence: 0.4, colorA: '#ffffff' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 300, height: 100 },
  },
  {
    id: 'flag-animations',
    name: 'Flag Animations',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'City'],
    effectTags: ['Environmental'],
    description: 'Waving flag or banner',
    performance: 'Light',
    defaultSettings: { speed: 0.5, turbulence: 0.6, colorA: '#cc0000', colorB: '#ffcc00' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 200, height: 150 },
  },
  {
    id: 'crowd-silhouettes',
    name: 'Crowd Silhouettes',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'City'],
    effectTags: ['Environmental'],
    description: 'Distant crowd movement',
    performance: 'Medium',
    defaultSettings: { speed: 0.2, density: 0.5, colorA: '#2d2d2d' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 400, height: 150 },
  },
  {
    id: 'wagon-traffic',
    name: 'Distant Wagon Traffic',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'City'],
    effectTags: ['Environmental'],
    description: 'Moving cart silhouettes',
    performance: 'Light',
    defaultSettings: { speed: 0.2, density: 0.2, colorA: '#4a3c31' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 400, height: 100 },
  },
  {
    id: 'harbor-cranes',
    name: 'Harbor Cranes Moving',
    category: 'city-settlement',
    genreTags: ['Fantasy', 'City', 'Steampunk'],
    effectTags: ['Environmental'],
    description: 'Dockside crane operation',
    performance: 'Medium',
    defaultSettings: { speed: 0.2 },
    baseComponent: 'MechanicalMotion',
    defaultSize: { width: 200, height: 300 },
  },

  // ========== HORROR & DARK FANTASY ==========
  {
    id: 'creeping-shadows',
    name: 'Creeping Shadows',
    category: 'horror-dark',
    genreTags: ['Horror', 'Fantasy'],
    effectTags: ['Magic', 'Environmental'],
    description: 'Moving darkness',
    performance: 'Medium',
    defaultSettings: { speed: 0.2, opacity: 0.7, colorA: '#0a0a0f' },
    baseComponent: 'ShadowCreep',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'blood-dripping',
    name: 'Blood Dripping',
    category: 'horror-dark',
    genreTags: ['Horror'],
    effectTags: ['Environmental'],
    description: 'Dripping blood effect',
    performance: 'Light',
    defaultSettings: { speed: 0.5, density: 0.3, colorA: '#8b0000', colorB: '#4a0000' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 200, height: 300 },
  },
  {
    id: 'ghostly-figures',
    name: 'Ghostly Figures Appearing',
    category: 'horror-dark',
    genreTags: ['Horror', 'Fantasy'],
    effectTags: ['Creature', 'Magic'],
    description: 'Fading ghost forms',
    performance: 'Medium',
    defaultSettings: { speed: 0.1, opacity: 0.4, glow: 0.5, colorA: '#b8c6db' },
    baseComponent: 'ShadowCreep',
    defaultSize: { width: 200, height: 350 },
  },
  {
    id: 'haunted-mist',
    name: 'Haunted Mist',
    category: 'horror-dark',
    genreTags: ['Horror', 'Fantasy'],
    effectTags: ['Weather', 'Magic'],
    description: 'Eerie swirling mist',
    performance: 'Medium',
    defaultSettings: { speed: 0.2, density: 0.6, colorA: '#4a4a5a', colorB: '#2a2a3a' },
    baseComponent: 'SmokeFog',
    defaultSize: { width: 500, height: 300 },
  },
  {
    id: 'eyes-darkness',
    name: 'Eyes in Darkness Blinking',
    category: 'horror-dark',
    genreTags: ['Horror'],
    effectTags: ['Creature'],
    description: 'Watching eyes in shadows',
    performance: 'Light',
    defaultSettings: { flicker: 0.3, density: 0.2, colorA: '#ffcc00' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 300, height: 200 },
  },
  {
    id: 'skull-spirits',
    name: 'Floating Skull Spirits',
    category: 'horror-dark',
    genreTags: ['Horror', 'Fantasy'],
    effectTags: ['Creature', 'Magic'],
    description: 'Spectral skull wisps',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, glow: 0.6, density: 0.2, colorA: '#88ff88' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'flesh-growths',
    name: 'Pulsing Flesh Growths',
    category: 'horror-dark',
    genreTags: ['Horror'],
    effectTags: ['Environmental'],
    description: 'Organic pulsing masses',
    performance: 'Medium',
    defaultSettings: { pulseRate: 0.4, colorA: '#8b4553', colorB: '#5a2d3a' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 250, height: 250 },
  },
  {
    id: 'graveyard-specters',
    name: 'Graveyard Specters',
    category: 'horror-dark',
    genreTags: ['Horror', 'Fantasy'],
    effectTags: ['Creature', 'Magic'],
    description: 'Cemetery ghost forms',
    performance: 'Medium',
    defaultSettings: { speed: 0.15, opacity: 0.5, glow: 0.4, colorA: '#a8b5c4' },
    baseComponent: 'ShadowCreep',
    defaultSize: { width: 300, height: 400 },
  },
  {
    id: 'shadow-tentacles',
    name: 'Shadow Tentacles',
    category: 'horror-dark',
    genreTags: ['Horror', 'Fantasy'],
    effectTags: ['Creature', 'Magic'],
    description: 'Dark writhing tendrils',
    performance: 'Heavy',
    defaultSettings: { speed: 0.4, turbulence: 0.7, colorA: '#1a0a1a' },
    baseComponent: 'ShadowCreep',
    defaultSize: { width: 300, height: 400 },
  },
  {
    id: 'whispering-faces',
    name: 'Whispering Faces in Walls',
    category: 'horror-dark',
    genreTags: ['Horror'],
    effectTags: ['Magic', 'Environmental'],
    description: 'Faces emerging from surfaces',
    performance: 'Medium',
    defaultSettings: { speed: 0.1, opacity: 0.3, density: 0.2, colorA: '#4a4a5a' },
    baseComponent: 'ShadowCreep',
    defaultSize: { width: 400, height: 300 },
  },

  // ========== SCI-FI ==========
  {
    id: 'holographic-billboards',
    name: 'Holographic Billboards',
    category: 'sci-fi',
    genreTags: ['Sci-Fi', 'Cyberpunk'],
    effectTags: ['Light', 'Environmental'],
    description: 'Flickering holo displays',
    performance: 'Medium',
    defaultSettings: { flicker: 0.3, glow: 0.7, colorA: '#00ffff', colorB: '#ff00ff' },
    baseComponent: 'Glitch',
    defaultSize: { width: 300, height: 200 },
  },
  {
    id: 'neon-flicker',
    name: 'Neon Sign Flicker',
    category: 'sci-fi',
    genreTags: ['Sci-Fi', 'Cyberpunk', 'City'],
    effectTags: ['Light'],
    description: 'Buzzing neon sign',
    performance: 'Light',
    defaultSettings: { flicker: 0.4, glow: 0.8, colorA: '#ff0066' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 200, height: 100 },
  },
  {
    id: 'flying-traffic',
    name: 'Flying Traffic Lanes',
    category: 'sci-fi',
    genreTags: ['Sci-Fi', 'Cyberpunk'],
    effectTags: ['Environmental'],
    description: 'Aerial vehicle streams',
    performance: 'Medium',
    defaultSettings: { speed: 0.6, density: 0.4, colorA: '#ffffff', colorB: '#ff3333' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 500, height: 200 },
  },
  {
    id: 'energy-shields',
    name: 'Energy Shields',
    category: 'sci-fi',
    genreTags: ['Sci-Fi'],
    effectTags: ['Magic', 'Light'],
    description: 'Protective force barrier',
    performance: 'Medium',
    defaultSettings: { glow: 0.7, turbulence: 0.3, colorA: '#00ccff', colorB: '#0066ff' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 300, height: 400 },
  },
  {
    id: 'plasma-conduits',
    name: 'Plasma Conduits',
    category: 'sci-fi',
    genreTags: ['Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Flowing energy tubes',
    performance: 'Medium',
    defaultSettings: { speed: 0.5, glow: 0.8, colorA: '#00ff00', colorB: '#00ffff' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 300, height: 100 },
  },
  {
    id: 'reactor-core',
    name: 'Reactor Core Pulsing',
    category: 'sci-fi',
    genreTags: ['Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Power core emanation',
    performance: 'Heavy',
    defaultSettings: { pulseRate: 0.5, glow: 0.9, colorA: '#00ffff', colorB: '#ffffff' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'computer-monitors',
    name: 'Computer Monitors Cycling',
    category: 'sci-fi',
    genreTags: ['Sci-Fi', 'Cyberpunk'],
    effectTags: ['Light', 'Environmental'],
    description: 'Scrolling screen data',
    performance: 'Light',
    defaultSettings: { speed: 0.5, flicker: 0.2, colorA: '#00ff00' },
    baseComponent: 'Glitch',
    defaultSize: { width: 200, height: 150 },
  },
  {
    id: 'laser-grid',
    name: 'Laser Security Grids',
    category: 'sci-fi',
    genreTags: ['Sci-Fi'],
    effectTags: ['Light'],
    description: 'Intersecting laser beams',
    performance: 'Medium',
    defaultSettings: { intensity: 0.8, colorA: '#ff0000' },
    baseComponent: 'BeamSweep',
    defaultSize: { width: 400, height: 300 },
  },
  {
    id: 'drone-patrols',
    name: 'Drone Patrols',
    category: 'sci-fi',
    genreTags: ['Sci-Fi', 'Cyberpunk'],
    effectTags: ['Creature', 'Environmental'],
    description: 'Flying surveillance drones',
    performance: 'Medium',
    defaultSettings: { speed: 0.4, density: 0.2, glow: 0.4, colorA: '#333333' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 400, height: 300 },
  },
  {
    id: 'holo-ads',
    name: 'Hologram Advertisements',
    category: 'sci-fi',
    genreTags: ['Sci-Fi', 'Cyberpunk'],
    effectTags: ['Light', 'Environmental'],
    description: 'Projected holo display',
    performance: 'Medium',
    defaultSettings: { flicker: 0.2, glow: 0.6, opacity: 0.7, colorA: '#00ffff', colorB: '#ff66cc' },
    baseComponent: 'Glitch',
    defaultSize: { width: 250, height: 350 },
  },
  {
    id: 'docking-lights',
    name: 'Docking Bay Lights',
    category: 'sci-fi',
    genreTags: ['Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Flashing guide lights',
    performance: 'Light',
    defaultSettings: { flicker: 0.6, colorA: '#ffcc00', colorB: '#ff3300' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 300, height: 100 },
  },
  {
    id: 'spaceship-launch',
    name: 'Spaceship Launches',
    category: 'sci-fi',
    genreTags: ['Sci-Fi'],
    effectTags: ['Set Piece', 'Fire'],
    description: 'Rocket exhaust trail',
    performance: 'Heavy',
    defaultSettings: { speed: 0.8, intensity: 0.9, glow: 0.9, colorA: '#ff6600', colorB: '#ffffff' },
    baseComponent: 'FlameFlicker',
    defaultSize: { width: 200, height: 400 },
  },
  {
    id: 'weapon-scars',
    name: 'Energy Weapon Discharge Scars',
    category: 'sci-fi',
    genreTags: ['Sci-Fi'],
    effectTags: ['Environmental'],
    description: 'Glowing impact marks',
    performance: 'Light',
    defaultSettings: { glow: 0.6, colorA: '#ff3300', colorB: '#ffcc00' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 150, height: 150 },
  },
  {
    id: 'cryo-pods',
    name: 'Cryogenic Pod Status Lights',
    category: 'sci-fi',
    genreTags: ['Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Cryo chamber indicators',
    performance: 'Light',
    defaultSettings: { pulseRate: 0.3, glow: 0.5, colorA: '#00ccff' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 100, height: 200 },
  },
  {
    id: 'warp-gate',
    name: 'Warp Gate Effects',
    category: 'sci-fi',
    genreTags: ['Sci-Fi'],
    effectTags: ['Magic', 'Light', 'Set Piece'],
    description: 'FTL jump portal',
    performance: 'Heavy',
    defaultSettings: { speed: 0.7, glow: 1, turbulence: 0.8, colorA: '#9966ff', colorB: '#00ffff' },
    baseComponent: 'Portal',
    defaultSize: { width: 350, height: 350 },
  },

  // ========== CYBERPUNK ==========
  {
    id: 'glitch-distortion',
    name: 'Glitch Distortions',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk', 'Sci-Fi'],
    effectTags: ['Environmental'],
    description: 'Digital corruption effect',
    performance: 'Medium',
    defaultSettings: { flicker: 0.7, intensity: 0.6, colorA: '#ff0066', colorB: '#00ffff' },
    baseComponent: 'Glitch',
    defaultSize: { width: 300, height: 200 },
  },
  {
    id: 'digital-rain',
    name: 'Digital Rain',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk', 'Sci-Fi'],
    effectTags: ['Environmental'],
    description: 'Matrix-style code rain',
    performance: 'Medium',
    defaultSettings: { speed: 0.6, density: 0.7, colorA: '#00ff00' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 400, height: 400 },
  },
  {
    id: 'data-streams',
    name: 'Data Streams',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk', 'Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Flowing data visualization',
    performance: 'Medium',
    defaultSettings: { speed: 0.7, glow: 0.6, colorA: '#00ffff', colorB: '#ff00ff' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 400, height: 150 },
  },
  {
    id: 'ar-ads',
    name: 'AR Advertisements',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk'],
    effectTags: ['Light', 'Environmental'],
    description: 'Augmented reality overlays',
    performance: 'Medium',
    defaultSettings: { flicker: 0.3, glow: 0.5, opacity: 0.6, colorA: '#ff66cc', colorB: '#66ccff' },
    baseComponent: 'Glitch',
    defaultSize: { width: 250, height: 200 },
  },
  {
    id: 'surveillance-scan',
    name: 'Surveillance Cameras Scanning',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk', 'Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Sweeping camera view cone',
    performance: 'Light',
    defaultSettings: { speed: 0.3, angle: 45, colorA: '#ff3300' },
    baseComponent: 'BeamSweep',
    defaultSize: { width: 200, height: 200 },
  },
  {
    id: 'hacked-sparks',
    name: 'Hacked System Sparks',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk', 'Sci-Fi'],
    effectTags: ['Light', 'Fire'],
    description: 'Electrical malfunction',
    performance: 'Medium',
    defaultSettings: { flicker: 0.8, intensity: 0.7, colorA: '#ffffff', colorB: '#00ffff' },
    baseComponent: 'Lightning',
    defaultSize: { width: 150, height: 150 },
  },
  {
    id: 'neon-reflections',
    name: 'Neon Reflections on Wet Streets',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk', 'City'],
    effectTags: ['Light', 'Water'],
    description: 'Wet street light reflections',
    performance: 'Medium',
    defaultSettings: { glow: 0.5, turbulence: 0.3, colorA: '#ff0066', colorB: '#00ffff' },
    baseComponent: 'RippleWave',
    defaultSize: { width: 400, height: 200 },
  },
  {
    id: 'facial-scan',
    name: 'Facial Recognition Scan Beams',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk', 'Sci-Fi'],
    effectTags: ['Light'],
    description: 'Scanning laser grid',
    performance: 'Light',
    defaultSettings: { speed: 0.5, colorA: '#00ff00' },
    baseComponent: 'BeamSweep',
    defaultSize: { width: 150, height: 200 },
  },
  {
    id: 'floating-ui',
    name: 'Floating UI Overlays',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk', 'Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Holographic interface elements',
    performance: 'Light',
    defaultSettings: { glow: 0.5, opacity: 0.7, colorA: '#00ccff' },
    baseComponent: 'Glitch',
    defaultSize: { width: 200, height: 150 },
  },
  {
    id: 'corp-logos',
    name: 'Corporate Logo Projections',
    category: 'cyberpunk',
    genreTags: ['Cyberpunk', 'City'],
    effectTags: ['Light', 'Environmental'],
    description: 'Building-side holo logo',
    performance: 'Medium',
    defaultSettings: { glow: 0.7, pulseRate: 0.2, colorA: '#ff0066', colorB: '#ffffff' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 300, height: 300 },
  },

  // ========== STEAMPUNK ==========
  {
    id: 'steam-vents',
    name: 'Steam Vents',
    category: 'steampunk',
    genreTags: ['Steampunk', 'Fantasy'],
    effectTags: ['Environmental'],
    description: 'Hissing steam release',
    performance: 'Light',
    defaultSettings: { speed: 0.6, density: 0.5, colorA: '#ffffff', colorB: '#d3d3d3' },
    baseComponent: 'SmokeFog',
    defaultSize: { width: 150, height: 250 },
  },
  {
    id: 'rotating-gears',
    name: 'Rotating Gears',
    category: 'steampunk',
    genreTags: ['Steampunk'],
    effectTags: ['Environmental'],
    description: 'Spinning gear mechanisms',
    performance: 'Light',
    defaultSettings: { speed: 0.4, colorA: '#b87333' },
    baseComponent: 'MechanicalMotion',
    defaultSize: { width: 200, height: 200 },
  },
  {
    id: 'clockwork',
    name: 'Clockwork Mechanisms',
    category: 'steampunk',
    genreTags: ['Steampunk'],
    effectTags: ['Environmental'],
    description: 'Complex gear assembly',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, density: 0.6, colorA: '#cd7f32', colorB: '#8b4513' },
    baseComponent: 'MechanicalMotion',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'pressure-gauges',
    name: 'Pressure Gauges Moving',
    category: 'steampunk',
    genreTags: ['Steampunk'],
    effectTags: ['Environmental'],
    description: 'Fluctuating gauge needles',
    performance: 'Light',
    defaultSettings: { speed: 0.4, turbulence: 0.3 },
    baseComponent: 'MechanicalMotion',
    defaultSize: { width: 100, height: 100 },
  },
  {
    id: 'piston-engines',
    name: 'Piston Engines Pumping',
    category: 'steampunk',
    genreTags: ['Steampunk'],
    effectTags: ['Environmental'],
    description: 'Rhythmic piston movement',
    performance: 'Medium',
    defaultSettings: { speed: 0.5 },
    baseComponent: 'MechanicalMotion',
    defaultSize: { width: 200, height: 250 },
  },
  {
    id: 'airship-shadows',
    name: 'Airship Shadows Overhead',
    category: 'steampunk',
    genreTags: ['Steampunk', 'Fantasy'],
    effectTags: ['Environmental', 'Set Piece'],
    description: 'Passing airship silhouettes',
    performance: 'Light',
    defaultSettings: { speed: 0.2, scale: 0.8, colorA: '#2d2d2d' },
    baseComponent: 'ShadowCreep',
    defaultSize: { width: 500, height: 200 },
  },
  {
    id: 'mechanical-walkers',
    name: 'Mechanical Walkers',
    category: 'steampunk',
    genreTags: ['Steampunk'],
    effectTags: ['Creature', 'Environmental'],
    description: 'Walking machine silhouettes',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, colorA: '#4a3c31' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 300, height: 300 },
  },
  {
    id: 'brass-machinery',
    name: 'Brass Machinery',
    category: 'steampunk',
    genreTags: ['Steampunk'],
    effectTags: ['Environmental'],
    description: 'Polished brass reflections',
    performance: 'Light',
    defaultSettings: { glow: 0.4, colorA: '#b87333', colorB: '#ffd700' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 250, height: 200 },
  },
  {
    id: 'conveyor-belts',
    name: 'Conveyor Belts',
    category: 'steampunk',
    genreTags: ['Steampunk'],
    effectTags: ['Environmental'],
    description: 'Moving factory belt',
    performance: 'Light',
    defaultSettings: { speed: 0.4, colorA: '#4a4a4a' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 400, height: 100 },
  },
  {
    id: 'boiler-release',
    name: 'Boiler Pressure Releases',
    category: 'steampunk',
    genreTags: ['Steampunk'],
    effectTags: ['Environmental', 'Fire'],
    description: 'Steam burst with sparks',
    performance: 'Medium',
    defaultSettings: { speed: 0.7, density: 0.6, colorA: '#ffffff', colorB: '#ff6600' },
    baseComponent: 'SmokeFog',
    defaultSize: { width: 200, height: 300 },
  },

  // ========== WASTELAND / POST-APOCALYPSE ==========
  {
    id: 'radiation-storm',
    name: 'Radiation Storms',
    category: 'wasteland',
    genreTags: ['Wasteland', 'Sci-Fi'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Green-tinted rad storm',
    performance: 'Heavy',
    defaultSettings: { speed: 0.7, density: 0.6, glow: 0.5, colorA: '#39ff14', colorB: '#00ff00' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 500, height: 400 },
  },
  {
    id: 'geiger-pulses',
    name: 'Geiger Counter Pulses',
    category: 'wasteland',
    genreTags: ['Wasteland', 'Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Radiation detection clicks',
    performance: 'Light',
    defaultSettings: { flicker: 0.6, glow: 0.4, colorA: '#39ff14' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 100, height: 100 },
  },
  {
    id: 'toxic-gas',
    name: 'Toxic Gas Clouds',
    category: 'wasteland',
    genreTags: ['Wasteland', 'Sci-Fi', 'Horror'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Poisonous gas drift',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, density: 0.6, colorA: '#9acd32', colorB: '#556b2f' },
    baseComponent: 'SmokeFog',
    defaultSize: { width: 400, height: 250 },
  },
  {
    id: 'dust-devils',
    name: 'Dust Devils',
    category: 'wasteland',
    genreTags: ['Wasteland', 'Nature'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Small swirling dust',
    performance: 'Medium',
    defaultSettings: { speed: 0.6, turbulence: 0.8, colorA: '#d2b48c' },
    baseComponent: 'Portal',
    defaultSize: { width: 150, height: 250 },
  },
  {
    id: 'burning-oil',
    name: 'Burning Oil Pits',
    category: 'wasteland',
    genreTags: ['Wasteland'],
    effectTags: ['Fire', 'Environmental'],
    description: 'Flaming oil pools',
    performance: 'Medium',
    defaultSettings: { speed: 0.5, intensity: 0.7, colorA: '#ff4500', colorB: '#1a1a1a' },
    baseComponent: 'FlameFlicker',
    defaultSize: { width: 300, height: 200 },
  },
  {
    id: 'nuclear-fallout',
    name: 'Nuclear Fallout',
    category: 'wasteland',
    genreTags: ['Wasteland', 'Sci-Fi'],
    effectTags: ['Weather', 'Environmental'],
    description: 'Radioactive ash drift',
    performance: 'Medium',
    defaultSettings: { speed: 0.3, density: 0.5, glow: 0.3, colorA: '#808080', colorB: '#39ff14' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 500, height: 400 },
  },
  {
    id: 'mutant-plants',
    name: 'Mutated Plant Movement',
    category: 'wasteland',
    genreTags: ['Wasteland', 'Horror'],
    effectTags: ['Creature', 'Environmental'],
    description: 'Twitching mutant flora',
    performance: 'Light',
    defaultSettings: { speed: 0.2, turbulence: 0.4, colorA: '#556b2f', colorB: '#9acd32' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 300, height: 200 },
  },
  {
    id: 'warning-sirens',
    name: 'Warning Siren Lights',
    category: 'wasteland',
    genreTags: ['Wasteland', 'Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Rotating red warning',
    performance: 'Light',
    defaultSettings: { speed: 0.5, glow: 0.7, colorA: '#ff0000' },
    baseComponent: 'BeamSweep',
    defaultSize: { width: 200, height: 200 },
  },
  {
    id: 'emergency-flicker',
    name: 'Flickering Emergency Systems',
    category: 'wasteland',
    genreTags: ['Wasteland', 'Sci-Fi'],
    effectTags: ['Light', 'Environmental'],
    description: 'Failing power lights',
    performance: 'Light',
    defaultSettings: { flicker: 0.7, glow: 0.5, colorA: '#ff3300', colorB: '#ffcc00' },
    baseComponent: 'GlowPulse',
    defaultSize: { width: 150, height: 100 },
  },
  {
    id: 'collapsing-debris',
    name: 'Collapsing Debris',
    category: 'wasteland',
    genreTags: ['Wasteland'],
    effectTags: ['Environmental', 'Set Piece'],
    description: 'Falling rubble particles',
    performance: 'Medium',
    defaultSettings: { speed: 0.7, density: 0.4, colorA: '#808080', colorB: '#4a4a4a' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 300, height: 400 },
  },

  // ========== LARGE SET-PIECE EFFECTS ==========
  {
    id: 'earthquake',
    name: 'Earthquakes',
    category: 'set-pieces',
    genreTags: ['Fantasy', 'Wasteland', 'Nature'],
    effectTags: ['Set Piece', 'Environmental'],
    description: 'Screen-shaking tremors',
    performance: 'Heavy',
    defaultSettings: { speed: 0.8, intensity: 0.7, turbulence: 0.9 },
    baseComponent: 'SetPieceShake',
    defaultSize: { width: 600, height: 400 },
  },
  {
    id: 'meteor-impacts',
    name: 'Meteor Impacts',
    category: 'set-pieces',
    genreTags: ['Fantasy', 'Sci-Fi', 'Wasteland'],
    effectTags: ['Set Piece', 'Fire'],
    description: 'Falling meteors with trails',
    performance: 'Heavy',
    defaultSettings: { speed: 0.9, intensity: 0.9, glow: 0.8, colorA: '#ff4500', colorB: '#ffcc00' },
    baseComponent: 'ParticleField',
    defaultSize: { width: 400, height: 500 },
  },
  {
    id: 'volcano-eruption',
    name: 'Volcano Eruptions',
    category: 'set-pieces',
    genreTags: ['Fantasy', 'Wasteland'],
    effectTags: ['Set Piece', 'Fire'],
    description: 'Explosive volcanic activity',
    performance: 'Heavy',
    defaultSettings: { speed: 0.8, intensity: 1, glow: 0.9, colorA: '#ff3300', colorB: '#ffcc00' },
    baseComponent: 'FlameFlicker',
    defaultSize: { width: 400, height: 600 },
  },
  {
    id: 'tsunami-waves',
    name: 'Tsunami Waves',
    category: 'set-pieces',
    genreTags: ['Fantasy', 'Nature'],
    effectTags: ['Set Piece', 'Water'],
    description: 'Massive approaching wave',
    performance: 'Heavy',
    defaultSettings: { speed: 0.6, scale: 1, colorA: '#1e5f8a', colorB: '#ffffff' },
    baseComponent: 'WaveFlow',
    defaultSize: { width: 600, height: 400 },
  },
  {
    id: 'arcane-storm',
    name: 'Arcane Storm Fronts',
    category: 'set-pieces',
    genreTags: ['Fantasy'],
    effectTags: ['Set Piece', 'Magic', 'Weather'],
    description: 'Magical weather phenomenon',
    performance: 'Heavy',
    defaultSettings: { speed: 0.6, intensity: 0.9, glow: 0.8, colorA: '#9966ff', colorB: '#ff66cc' },
    baseComponent: 'SmokeFog',
    defaultSize: { width: 600, height: 400 },
  },
  {
    id: 'battlefield-bombardment',
    name: 'Battlefield Bombardments',
    category: 'set-pieces',
    genreTags: ['Fantasy', 'Wasteland', 'Sci-Fi'],
    effectTags: ['Set Piece', 'Fire'],
    description: 'Explosive impacts',
    performance: 'Heavy',
    defaultSettings: { speed: 0.8, density: 0.6, flicker: 0.9, colorA: '#ff4500', colorB: '#ffcc00' },
    baseComponent: 'FlameFlicker',
    defaultSize: { width: 500, height: 400 },
  },
  {
    id: 'airship-battle',
    name: 'Airship Battles Overhead',
    category: 'set-pieces',
    genreTags: ['Fantasy', 'Steampunk'],
    effectTags: ['Set Piece', 'Environmental'],
    description: 'Aerial combat above',
    performance: 'Heavy',
    defaultSettings: { speed: 0.4, density: 0.3, colorA: '#2d2d2d', colorB: '#ff6600' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 600, height: 300 },
  },
  {
    id: 'dragon-attack',
    name: 'Dragon Attack Flyovers',
    category: 'set-pieces',
    genreTags: ['Fantasy'],
    effectTags: ['Set Piece', 'Creature', 'Fire'],
    description: 'Dragon strafing run',
    performance: 'Heavy',
    defaultSettings: { speed: 0.6, intensity: 0.9, colorA: '#ff4500', colorB: '#2d2d2d' },
    baseComponent: 'SwarmMovement',
    defaultSize: { width: 500, height: 300 },
  },
  {
    id: 'orbital-bombardment',
    name: 'Orbital Bombardment',
    category: 'set-pieces',
    genreTags: ['Sci-Fi'],
    effectTags: ['Set Piece', 'Light', 'Fire'],
    description: 'Space-based weapon strike',
    performance: 'Heavy',
    defaultSettings: { speed: 1, intensity: 1, glow: 1, colorA: '#ffffff', colorB: '#00ffff' },
    baseComponent: 'BeamSweep',
    defaultSize: { width: 400, height: 600 },
  },
  {
    id: 'dimensional-rift',
    name: 'Dimensional Rift Tears',
    category: 'set-pieces',
    genreTags: ['Fantasy', 'Sci-Fi', 'Horror'],
    effectTags: ['Set Piece', 'Magic'],
    description: 'Reality-tearing portals',
    performance: 'Heavy',
    defaultSettings: { speed: 0.5, glow: 1, turbulence: 0.9, colorA: '#ff00ff', colorB: '#00ffff' },
    baseComponent: 'Portal',
    defaultSize: { width: 350, height: 500 },
  },
]

// Helper to get effects by category
export function getEffectsByCategory(category: EffectCategory): ExpandedEffectDefinition[] {
  return effectsLibrary.filter(e => e.category === category)
}

// Helper to search effects
export function searchEffects(query: string): ExpandedEffectDefinition[] {
  const lowerQuery = query.toLowerCase()
  return effectsLibrary.filter(e => 
    e.name.toLowerCase().includes(lowerQuery) ||
    e.description.toLowerCase().includes(lowerQuery) ||
    e.category.includes(lowerQuery) ||
    e.genreTags.some(t => t.toLowerCase().includes(lowerQuery)) ||
    e.effectTags.some(t => t.toLowerCase().includes(lowerQuery))
  )
}

// Helper to filter by tags
export function filterEffectsByTags(
  genreTags?: GenreTag[],
  effectTags?: EffectTypeTag[]
): ExpandedEffectDefinition[] {
  return effectsLibrary.filter(e => {
    const matchesGenre = !genreTags?.length || genreTags.some(t => e.genreTags.includes(t))
    const matchesEffect = !effectTags?.length || effectTags.some(t => e.effectTags.includes(t))
    return matchesGenre && matchesEffect
  })
}
