// Curated Effects Library - Reorganized into Core, Atmospheric, and Terrain Packs

export type EffectPack = 'core' | 'atmospheric' | 'terrain' | 'fantasy' | 'magic' | 'scifi' | 'launch' | 'caustics' | 'rain' | 'cemetery' | 'subterranean' | 'lightsource' | 'lightsource-revised' | 'new'

export type EffectId = 
  // Core Pack (7) - Localized light sources
  | 'torch' | 'torch-2' | 'campfire' | 'lantern' | 'candles' | 'brazier' | 'magical-light'
  // Atmospheric Pack (8) - Full-area weather/environment overlays
  | 'rain' | 'snow' | 'fog' | 'mist' | 'wind' | 'lightning-storm' | 'dust-storm' | 'blizzard'
  // Terrain Pack (6) - Ground/surface effects
  | 'water-ripples' | 'waterfall' | 'lava-flow' | 'swamp-bubbles' | 'ice-crystals' | 'smoke-vents'
  // Fantasy Pack (6)
  | 'arcane-circles' | 'portals' | 'floating-runes' | 'divine-light' | 'necrotic-corruption' | 'spirit-apparitions'
  // Magic Effects Pack (17) - portal gateways + magic-circle sprite-sheet animations
  | 'blue-portal' | 'fire-portal'
  | 'magic-golden-arcane' | 'magic-cyan-heptagram' | 'magic-purple-hexagram' | 'magic-verdant-summoning' | 'magic-infernal-flame'
  | 'magic-radiant-ward' | 'magic-magenta-hex' | 'magic-golden-rune' | 'magic-azure-conjuration' | 'magic-violet-enchantment'
  | 'magic-emerald-nature' | 'magic-spiral-vortex' | 'magic-crimson-pentagram' | 'magic-amber-alchemy' | 'magic-frost-sigil'
  // Sci-Fi Pack (4)
  | 'holograms' | 'energy-shields' | 'data-streams' | 'reactor-core'
  // Launch Effects Pack (15) - sprite-sheet animations
  | 'launch-torch-light' | 'launch-lantern-glow' | 'launch-campfire' | 'launch-smoke-wisps' | 'launch-running-water'
  | 'launch-rain' | 'launch-fog' | 'launch-floating-dust' | 'launch-fireflies' | 'launch-arcane-runes'
  | 'launch-portal' | 'launch-lightning' | 'launch-divine-light' | 'launch-necrotic-corruption' | 'launch-ghost-apparition'
  // Caustics Pack (15) - underwater light sprite-sheet animations
  | 'caustics-shallow-clear' | 'caustics-deep-blue' | 'caustics-tropical-shallow' | 'caustics-soft-sand' | 'caustics-rocky-bottom'
  | 'caustics-fast-moving' | 'caustics-slow-gentle' | 'caustics-blue-green' | 'caustics-sunlit-deep' | 'caustics-murky-water'
  | 'caustics-cave-water' | 'caustics-kelp-forest' | 'caustics-rippling-sand' | 'caustics-wavy-surface' | 'caustics-magic-glow'
  // Rain Effects Pack (15) - rain sprite-sheet animations
  | 'rain-light-drizzle' | 'rain-steady' | 'rain-heavy' | 'rain-torrential' | 'rain-wind-blown'
  | 'rain-fine-mist' | 'rain-sheet' | 'rain-intermittent' | 'rain-splatter-spray' | 'rain-ground-mist'
  | 'rain-micro-drizzle' | 'rain-sideways' | 'rain-fog-mix' | 'rain-droplet-impacts' | 'rain-dynamic-storm'
  // Cemetery Effects Pack (15) - spooky sprite-sheet animations
  | 'cemetery-graveyard-fog' | 'cemetery-will-o-wisps' | 'cemetery-soul-spirits' | 'cemetery-necrotic-aura' | 'cemetery-blood-petals'
  | 'cemetery-haunted-lantern' | 'cemetery-cracked-stone-rise' | 'cemetery-skeletal-remains' | 'cemetery-dark-ritual-circle' | 'cemetery-coffin-burst'
  | 'cemetery-ethereal-mist-swirl' | 'cemetery-moonbeam-trees' | 'cemetery-draining-life-vortex' | 'cemetery-candle-flame' | 'cemetery-bats-in-flight'
  // Subterranean Effects Pack (15) - cave sprite-sheet animations
  | 'subterranean-cave-drips' | 'subterranean-stalactite-seep' | 'subterranean-underground-stream' | 'subterranean-cave-mist' | 'subterranean-crystal-sparkles'
  | 'subterranean-crystal-pulse' | 'subterranean-bioluminescent-spores' | 'subterranean-glowing-mushroom-aura' | 'subterranean-bat-swarm' | 'subterranean-dustfall'
  | 'subterranean-pebble-collapse' | 'subterranean-steam-vent' | 'subterranean-cave-fireflies' | 'subterranean-arcane-cave-energy' | 'subterranean-ambient'
  // Light Source Effects Pack (15) - illumination sprite-sheet animations
  | 'lightsource-wall-torch' | 'lightsource-ornate-lantern' | 'lightsource-iron-lantern' | 'lightsource-hanging-lantern' | 'lightsource-carriage-lantern'
  | 'lightsource-campfire' | 'lightsource-sparkler-burst' | 'lightsource-candle' | 'lightsource-glowing-orb' | 'lightsource-fire-brazier'
  | 'lightsource-rune-light-circle' | 'lightsource-pendant-light' | 'lightsource-radiant-starburst' | 'lightsource-soft-star-glow' | 'lightsource-sparkle-starburst'
  // Light Source Revised Effects Pack (15) - sprite sheets sliced from source grid
  | 'lsr-torch' | 'lsr-fire-glow' | 'lsr-fire-bowl' | 'lsr-carriage-lantern' | 'lsr-hanging-lantern'
  | 'lsr-candle' | 'lsr-glowing-orb' | 'lsr-campfire' | 'lsr-sparkles' | 'lsr-fire-brazier'
  | 'lsr-blue-flame' | 'lsr-green-flame' | 'lsr-starburst' | 'lsr-arcane-circle' | 'lsr-smoke'
  // NEW EFFECTS PACK — auto-generated, do not edit this line
  | 'new-fire-torch'
  | 'new-smoke'
  // NEW_EFFECT_IDS

export type RenderMode = 'localized' | 'atmospheric' | 'terrain'

export interface EffectSettings {
  speed: number        // 0-100
  intensity: number    // 0-100
  density: number      // 0-100
  color: string        // hex color
  secondaryColor?: string
  scale: number        // 0.1-3
  direction?: number   // 0-360 degrees
  flickerRate?: number // 0-100 for light effects
  glowIntensity?: number // 0-100
}

export interface EffectDefinition {
  id: EffectId
  name: string
  pack: EffectPack
  renderMode: RenderMode  // How the effect should be rendered
  icon: string
  defaultSettings: EffectSettings
  description: string
}

export const EFFECT_PACKS: Record<EffectPack, { name: string; icon: string; color: string; description: string }> = {
  core: { 
    name: 'Core', 
    icon: 'flame', 
    color: '#f59e0b',
    description: 'Light sources and illumination'
  },
  atmospheric: { 
    name: 'Atmospheric', 
    icon: 'cloud', 
    color: '#64748b',
    description: 'Weather and environmental overlays'
  },
  terrain: { 
    name: 'Terrain', 
    icon: 'mountain', 
    color: '#22c55e',
    description: 'Ground and surface effects'
  },
  fantasy: { 
    name: 'Fantasy', 
    icon: 'sparkles', 
    color: '#8b5cf6',
    description: 'Magical and mystical effects'
  },
  magic: { 
    name: 'Magic Effects', 
    icon: 'sparkles', 
    color: '#a855f7',
    description: 'Magic circles, sigils, and arcane portals'
  },
  scifi: { 
    name: 'Sci-Fi', 
    icon: 'cpu', 
    color: '#06b6d4',
    description: 'Futuristic technology effects'
  },
  launch: { 
    name: 'Launch Effects', 
    icon: 'rocket', 
    color: '#10b981',
    description: 'Premium animated sprite effects'
  },
  caustics: { 
    name: 'Water Effects', 
    icon: 'waves', 
    color: '#38bdf8',
    description: 'Underwater light caustics'
  },
  rain: { 
    name: 'Rain Effects', 
    icon: 'cloud-rain', 
    color: '#60a5fa',
    description: 'Animated rain sprite effects'
  },
  cemetery: { 
    name: 'Cemetery Effects', 
    icon: 'skull', 
    color: '#22c55e',
    description: 'Spooky graveyard sprite effects'
  },
  subterranean: { 
    name: 'Subterranean Effects', 
    icon: 'gem', 
    color: '#22d3ee',
    description: 'Cave and underground sprite effects'
  },
  lightsource: { 
    name: 'Light Source Effects', 
    icon: 'lamp', 
    color: '#fbbf24',
    description: 'Torches, lanterns, and glowing light sprites'
  },
  'lightsource-revised': {
    name: 'Light Source Revised Effects',
    icon: 'lamp',
    color: '#f97316',
    description: 'Revised torches, lanterns, flames, and glowing light sprites'
  },
  new: {
    name: 'New Effects',
    icon: 'plus',
    color: '#6366f1',
    description: 'Newly imported sprite sheet effects'
  },
}

export const effectsLibrary: EffectDefinition[] = [
  // ===== CORE PACK - Light Sources =====
  {
    id: 'torch',
    name: 'Torch Light',
    pack: 'core',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Warm flickering light radius',
    defaultSettings: {
      speed: 50,
      intensity: 80,
      density: 30,
      color: '#ff9500',
      secondaryColor: '#ff4d00',
      flickerRate: 70,
      glowIntensity: 60,
      scale: 1,
    },
  },
  {
    id: 'torch-2',
    name: 'Torch Flame',
    pack: 'core',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Animated sprite flame effect',
    defaultSettings: {
      speed: 50,
      intensity: 80,
      density: 30,
      color: '#ff9500',
      secondaryColor: '#ff4d00',
      flickerRate: 70,
      glowIntensity: 60,
      scale: 1,
    },
  },
  {
    id: 'campfire',
    name: 'Campfire',
    pack: 'core',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Large warm glow with spark embers',
    defaultSettings: {
      speed: 45,
      intensity: 85,
      density: 50,
      color: '#ff6b00',
      secondaryColor: '#ffcc00',
      flickerRate: 60,
      glowIntensity: 70,
      scale: 1.2,
    },
  },
  {
    id: 'lantern',
    name: 'Lantern',
    pack: 'core',
    renderMode: 'localized',
    icon: 'lightbulb',
    description: 'Steady warm glow with subtle flicker',
    defaultSettings: {
      speed: 30,
      intensity: 70,
      density: 25,
      color: '#fbbf24',
      secondaryColor: '#f59e0b',
      flickerRate: 20,
      glowIntensity: 55,
      scale: 0.8,
    },
  },
  {
    id: 'candles',
    name: 'Candles',
    pack: 'core',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Small dancing flames with soft glow',
    defaultSettings: {
      speed: 40,
      intensity: 50,
      density: 20,
      color: '#fcd34d',
      secondaryColor: '#fbbf24',
      flickerRate: 80,
      glowIntensity: 40,
      scale: 0.5,
    },
  },
  {
    id: 'brazier',
    name: 'Brazier',
    pack: 'core',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Intense fire with large light radius',
    defaultSettings: {
      speed: 55,
      intensity: 95,
      density: 60,
      color: '#ef4444',
      secondaryColor: '#f97316',
      flickerRate: 50,
      glowIntensity: 85,
      scale: 1.5,
    },
  },
  {
    id: 'magical-light',
    name: 'Magical Light',
    pack: 'core',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Cool ethereal glow with sparkles',
    defaultSettings: {
      speed: 25,
      intensity: 75,
      density: 35,
      color: '#60a5fa',
      secondaryColor: '#c084fc',
      flickerRate: 30,
      glowIntensity: 70,
      scale: 1,
    },
  },

  // ===== ATMOSPHERIC PACK - Weather & Environment =====
  {
    id: 'rain',
    name: 'Rain',
    pack: 'atmospheric',
    renderMode: 'atmospheric',
    icon: 'cloud-rain',
    description: 'Falling rain with ground ripples',
    defaultSettings: {
      speed: 70,
      intensity: 60,
      density: 50,
      color: '#a8c8e8',
      direction: 180,
      scale: 1,
    },
  },
  {
    id: 'snow',
    name: 'Snowfall',
    pack: 'atmospheric',
    renderMode: 'atmospheric',
    icon: 'snowflake',
    description: 'Gentle drifting snowflakes',
    defaultSettings: {
      speed: 30,
      intensity: 50,
      density: 40,
      color: '#ffffff',
      scale: 1,
    },
  },
  {
    id: 'fog',
    name: 'Fog',
    pack: 'atmospheric',
    renderMode: 'atmospheric',
    icon: 'cloud',
    description: 'Thick rolling fog banks',
    defaultSettings: {
      speed: 15,
      intensity: 70,
      density: 80,
      color: '#d4d4d4',
      scale: 2,
    },
  },
  {
    id: 'mist',
    name: 'Mist',
    pack: 'atmospheric',
    renderMode: 'atmospheric',
    icon: 'cloud',
    description: 'Light ethereal haze',
    defaultSettings: {
      speed: 10,
      intensity: 40,
      density: 50,
      color: '#e5e7eb',
      scale: 1.5,
    },
  },
  {
    id: 'wind',
    name: 'Wind',
    pack: 'atmospheric',
    renderMode: 'atmospheric',
    icon: 'wind',
    description: 'Visible gusts with debris',
    defaultSettings: {
      speed: 60,
      intensity: 40,
      density: 25,
      color: '#e8e8e8',
      direction: 90,
      scale: 1,
    },
  },
  {
    id: 'lightning-storm',
    name: 'Lightning Storm',
    pack: 'atmospheric',
    renderMode: 'atmospheric',
    icon: 'zap',
    description: 'Dramatic sky flashes with rain',
    defaultSettings: {
      speed: 90,
      intensity: 100,
      density: 15,
      color: '#e8e8ff',
      secondaryColor: '#a8a8ff',
      flickerRate: 95,
      scale: 1,
    },
  },
  {
    id: 'dust-storm',
    name: 'Dust Storm',
    pack: 'atmospheric',
    renderMode: 'atmospheric',
    icon: 'wind',
    description: 'Swirling sand and dust particles',
    defaultSettings: {
      speed: 75,
      intensity: 65,
      density: 70,
      color: '#d4a574',
      secondaryColor: '#a8845c',
      direction: 45,
      scale: 1.2,
    },
  },
  {
    id: 'blizzard',
    name: 'Blizzard',
    pack: 'atmospheric',
    renderMode: 'atmospheric',
    icon: 'snowflake',
    description: 'Intense snow with howling wind',
    defaultSettings: {
      speed: 85,
      intensity: 80,
      density: 75,
      color: '#ffffff',
      secondaryColor: '#e0f2fe',
      direction: 60,
      scale: 1,
    },
  },

  // ===== TERRAIN PACK - Ground & Surface =====
  {
    id: 'water-ripples',
    name: 'Water Surface',
    pack: 'terrain',
    renderMode: 'terrain',
    icon: 'droplets',
    description: 'Gentle rippling water surface',
    defaultSettings: {
      speed: 40,
      intensity: 50,
      density: 30,
      color: '#4da6ff',
      secondaryColor: '#87ceeb',
      scale: 1,
    },
  },
  {
    id: 'waterfall',
    name: 'Waterfall',
    pack: 'terrain',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Cascading water with spray mist',
    defaultSettings: {
      speed: 80,
      intensity: 70,
      density: 60,
      color: '#87ceeb',
      secondaryColor: '#ffffff',
      scale: 1,
    },
  },
  {
    id: 'lava-flow',
    name: 'Lava Flow',
    pack: 'terrain',
    renderMode: 'terrain',
    icon: 'flame',
    description: 'Molten rock with glowing cracks',
    defaultSettings: {
      speed: 20,
      intensity: 90,
      density: 70,
      color: '#ff4500',
      secondaryColor: '#ff8c00',
      glowIntensity: 85,
      scale: 1,
    },
  },
  {
    id: 'swamp-bubbles',
    name: 'Swamp Bubbles',
    pack: 'terrain',
    renderMode: 'terrain',
    icon: 'droplets',
    description: 'Murky water with rising bubbles',
    defaultSettings: {
      speed: 25,
      intensity: 45,
      density: 35,
      color: '#4a5c4a',
      secondaryColor: '#6b8e6b',
      scale: 1,
    },
  },
  {
    id: 'ice-crystals',
    name: 'Ice Crystals',
    pack: 'terrain',
    renderMode: 'terrain',
    icon: 'gem',
    description: 'Frozen surface with shimmer',
    defaultSettings: {
      speed: 15,
      intensity: 60,
      density: 40,
      color: '#b3e0ff',
      secondaryColor: '#ffffff',
      glowIntensity: 40,
      scale: 1,
    },
  },
  {
    id: 'smoke-vents',
    name: 'Smoke Vents',
    pack: 'terrain',
    renderMode: 'terrain',
    icon: 'cloud',
    description: 'Rising smoke from ground cracks',
    defaultSettings: {
      speed: 30,
      intensity: 55,
      density: 45,
      color: '#4a4a4a',
      secondaryColor: '#6b6b6b',
      scale: 1,
    },
  },

  // ===== FANTASY PACK =====
  {
    id: 'arcane-circles',
    name: 'Arcane Circle',
    pack: 'fantasy',
    renderMode: 'localized',
    icon: 'circle',
    description: 'Rotating magical sigil',
    defaultSettings: {
      speed: 30,
      intensity: 70,
      density: 40,
      color: '#8b5cf6',
      secondaryColor: '#c084fc',
      glowIntensity: 80,
      scale: 1,
    },
  },
  {
    id: 'portals',
    name: 'Portal',
    pack: 'fantasy',
    renderMode: 'localized',
    icon: 'circle-dot',
    description: 'Swirling dimensional gateway',
    defaultSettings: {
      speed: 50,
      intensity: 90,
      density: 50,
      color: '#06b6d4',
      secondaryColor: '#8b5cf6',
      glowIntensity: 90,
      scale: 1,
    },
  },
  {
    id: 'floating-runes',
    name: 'Floating Runes',
    pack: 'fantasy',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Ancient glowing symbols',
    defaultSettings: {
      speed: 25,
      intensity: 60,
      density: 35,
      color: '#fbbf24',
      glowIntensity: 65,
      scale: 1,
    },
  },
  {
    id: 'divine-light',
    name: 'Divine Light',
    pack: 'fantasy',
    renderMode: 'localized',
    icon: 'sun',
    description: 'Heavenly rays from above',
    defaultSettings: {
      speed: 20,
      intensity: 80,
      density: 40,
      color: '#fef08a',
      secondaryColor: '#ffffff',
      glowIntensity: 95,
      scale: 1.2,
    },
  },
  {
    id: 'necrotic-corruption',
    name: 'Necrotic Corruption',
    pack: 'fantasy',
    renderMode: 'terrain',
    icon: 'skull',
    description: 'Dark spreading corruption',
    defaultSettings: {
      speed: 30,
      intensity: 70,
      density: 55,
      color: '#4a044e',
      secondaryColor: '#84cc16',
      glowIntensity: 50,
      scale: 1,
    },
  },
  {
    id: 'spirit-apparitions',
    name: 'Spirit Apparitions',
    pack: 'fantasy',
    renderMode: 'atmospheric',
    icon: 'ghost',
    description: 'Ghostly shapes drifting by',
    defaultSettings: {
      speed: 20,
      intensity: 50,
      density: 20,
      color: '#e0f2fe',
      glowIntensity: 60,
      scale: 1,
    },
  },
  {
    id: 'blue-portal',
    name: 'Blue Portal',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'circle-dot',
    description: 'Expanding arcane blue ring portal',
    defaultSettings: {
      speed: 50,
      intensity: 90,
      density: 50,
      color: '#22d3ee',
      secondaryColor: '#a5f3fc',
      glowIntensity: 90,
      scale: 1,
    },
  },
  {
    id: 'fire-portal',
    name: 'Fire Portal',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Erupting fiery portal sprite animation',
    defaultSettings: {
      speed: 50,
      intensity: 90,
      density: 50,
      color: '#ff8c1a',
      secondaryColor: '#ffcc66',
      glowIntensity: 90,
      scale: 1,
    },
  },

  // ===== SCI-FI PACK =====
  {
    id: 'holograms',
    name: 'Hologram',
    pack: 'scifi',
    renderMode: 'localized',
    icon: 'monitor',
    description: 'Flickering digital projection',
    defaultSettings: {
      speed: 60,
      intensity: 70,
      density: 45,
      color: '#06b6d4',
      flickerRate: 40,
      glowIntensity: 75,
      scale: 1,
    },
  },
  {
    id: 'energy-shields',
    name: 'Energy Shield',
    pack: 'scifi',
    renderMode: 'localized',
    icon: 'shield',
    description: 'Hexagonal force field',
    defaultSettings: {
      speed: 55,
      intensity: 75,
      density: 50,
      color: '#3b82f6',
      secondaryColor: '#60a5fa',
      glowIntensity: 80,
      scale: 1,
    },
  },
  {
    id: 'data-streams',
    name: 'Data Stream',
    pack: 'scifi',
    renderMode: 'localized',
    icon: 'binary',
    description: 'Cascading digital code',
    defaultSettings: {
      speed: 70,
      intensity: 65,
      density: 60,
      color: '#22c55e',
      scale: 1,
    },
  },
  {
    id: 'reactor-core',
    name: 'Reactor Core',
    pack: 'scifi',
    renderMode: 'localized',
    icon: 'atom',
    description: 'Pulsing energy source',
    defaultSettings: {
      speed: 45,
      intensity: 90,
      density: 40,
      color: '#f97316',
      secondaryColor: '#facc15',
      glowIntensity: 95,
      scale: 1,
    },
  },

  // ===== LAUNCH EFFECTS PACK - sprite-sheet animations (5x6, 30 frames) =====
  {
    id: 'launch-torch-light',
    name: 'Torch Light',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Flickering torch flame',
    defaultSettings: { speed: 50, intensity: 90, density: 50, color: '#ffae42', secondaryColor: '#ff6a00', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'launch-lantern-glow',
    name: 'Lantern Glow',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'lamp',
    description: 'Warm hanging lantern light',
    defaultSettings: { speed: 40, intensity: 80, density: 50, color: '#ffd166', secondaryColor: '#f59e0b', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'launch-campfire',
    name: 'Campfire',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Crackling campfire blaze',
    defaultSettings: { speed: 55, intensity: 95, density: 60, color: '#ff7a1a', secondaryColor: '#ffcc00', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'launch-smoke-wisps',
    name: 'Smoke Wisps',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'wind',
    description: 'Drifting wisps of smoke',
    defaultSettings: { speed: 35, intensity: 60, density: 50, color: '#e5e7eb', secondaryColor: '#9ca3af', glowIntensity: 40, scale: 1 },
  },
  {
    id: 'launch-running-water',
    name: 'Running Water',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'droplets',
    description: 'Splashing flowing water',
    defaultSettings: { speed: 60, intensity: 80, density: 60, color: '#7dd3fc', secondaryColor: '#bae6fd', glowIntensity: 60, scale: 1 },
  },
  {
    id: 'launch-rain',
    name: 'Rain',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'cloud-rain',
    description: 'Falling rain with splashes',
    defaultSettings: { speed: 70, intensity: 75, density: 70, color: '#e0f2fe', secondaryColor: '#ffffff', glowIntensity: 40, scale: 1 },
  },
  {
    id: 'launch-fog',
    name: 'Fog',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'cloud',
    description: 'Billowing fog clouds',
    defaultSettings: { speed: 30, intensity: 60, density: 60, color: '#f3f4f6', secondaryColor: '#d1d5db', glowIntensity: 30, scale: 1 },
  },
  {
    id: 'launch-floating-dust',
    name: 'Floating Dust',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Drifting motes of dust',
    defaultSettings: { speed: 25, intensity: 50, density: 40, color: '#fde68a', secondaryColor: '#fbbf24', glowIntensity: 50, scale: 1 },
  },
  {
    id: 'launch-fireflies',
    name: 'Fireflies',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'sparkle',
    description: 'Glowing dancing fireflies',
    defaultSettings: { speed: 45, intensity: 80, density: 40, color: '#fde047', secondaryColor: '#facc15', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'launch-arcane-runes',
    name: 'Arcane Runes',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Glowing magic rune circles',
    defaultSettings: { speed: 40, intensity: 85, density: 50, color: '#c084fc', secondaryColor: '#e9d5ff', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'launch-portal',
    name: 'Portal',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'circle-dot',
    description: 'Swirling magic portal rings',
    defaultSettings: { speed: 50, intensity: 90, density: 50, color: '#a855f7', secondaryColor: '#d8b4fe', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'launch-lightning',
    name: 'Lightning',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'zap',
    description: 'Crackling lightning bolts',
    defaultSettings: { speed: 80, intensity: 95, density: 50, color: '#bae6fd', secondaryColor: '#60a5fa', glowIntensity: 95, scale: 1 },
  },
  {
    id: 'launch-divine-light',
    name: 'Divine Light',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'sun',
    description: 'Radiant beams of holy light',
    defaultSettings: { speed: 40, intensity: 90, density: 50, color: '#fde68a', secondaryColor: '#fef9c3', glowIntensity: 95, scale: 1 },
  },
  {
    id: 'launch-necrotic-corruption',
    name: 'Necrotic Corruption',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'skull',
    description: 'Spreading necrotic energy',
    defaultSettings: { speed: 45, intensity: 85, density: 60, color: '#84cc16', secondaryColor: '#bef264', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'launch-ghost-apparition',
    name: 'Ghost Apparition',
    pack: 'launch',
    renderMode: 'localized',
    icon: 'ghost',
    description: 'Spectral ghostly figures',
    defaultSettings: { speed: 35, intensity: 70, density: 40, color: '#a5f3fc', secondaryColor: '#cffafe', glowIntensity: 80, scale: 1 },
  },

  // ===== CAUSTICS PACK - underwater light sprite sheets (5x5, 25 frames) =====
  {
    id: 'caustics-shallow-clear',
    name: 'Shallow Clear Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Crisp light ripples in shallow clear water',
    defaultSettings: { speed: 50, intensity: 80, density: 50, color: '#7dd3fc', secondaryColor: '#e0f2fe', glowIntensity: 70, scale: 1 },
  },
  {
    id: 'caustics-deep-blue',
    name: 'Deep Blue Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Cool caustics in deep blue water',
    defaultSettings: { speed: 40, intensity: 75, density: 55, color: '#3b82f6', secondaryColor: '#93c5fd', glowIntensity: 65, scale: 1 },
  },
  {
    id: 'caustics-tropical-shallow',
    name: 'Tropical Shallow Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Bright turquoise tropical caustics',
    defaultSettings: { speed: 55, intensity: 85, density: 50, color: '#2dd4bf', secondaryColor: '#a7f3d0', glowIntensity: 70, scale: 1 },
  },
  {
    id: 'caustics-soft-sand',
    name: 'Soft Sand Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Soft diffuse caustics over sand',
    defaultSettings: { speed: 45, intensity: 70, density: 50, color: '#bae6fd', secondaryColor: '#f0f9ff', glowIntensity: 60, scale: 1 },
  },
  {
    id: 'caustics-rocky-bottom',
    name: 'Rocky Bottom Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Caustics scattered over rocky bottom',
    defaultSettings: { speed: 48, intensity: 78, density: 55, color: '#67e8f9', secondaryColor: '#cffafe', glowIntensity: 65, scale: 1 },
  },
  {
    id: 'caustics-fast-moving',
    name: 'Fast Moving Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Rapidly shifting light patterns',
    defaultSettings: { speed: 80, intensity: 88, density: 50, color: '#22d3ee', secondaryColor: '#ecfeff', glowIntensity: 75, scale: 1 },
  },
  {
    id: 'caustics-slow-gentle',
    name: 'Slow Gentle Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Slow, calming light ripples',
    defaultSettings: { speed: 25, intensity: 65, density: 45, color: '#5eead4', secondaryColor: '#ccfbf1', glowIntensity: 55, scale: 1 },
  },
  {
    id: 'caustics-blue-green',
    name: 'Blue Green Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Blended blue-green water caustics',
    defaultSettings: { speed: 50, intensity: 80, density: 50, color: '#14b8a6', secondaryColor: '#99f6e4', glowIntensity: 68, scale: 1 },
  },
  {
    id: 'caustics-sunlit-deep',
    name: 'Sunlit Deep Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Sun rays piercing deep water',
    defaultSettings: { speed: 42, intensity: 82, density: 55, color: '#60a5fa', secondaryColor: '#dbeafe', glowIntensity: 72, scale: 1 },
  },
  {
    id: 'caustics-murky-water',
    name: 'Murky Water Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Hazy caustics in murky green water',
    defaultSettings: { speed: 38, intensity: 60, density: 60, color: '#84cc16', secondaryColor: '#d9f99d', glowIntensity: 50, scale: 1 },
  },
  {
    id: 'caustics-cave-water',
    name: 'Cave Water Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Stark caustics in dark cave water',
    defaultSettings: { speed: 35, intensity: 85, density: 45, color: '#bfdbfe', secondaryColor: '#ffffff', glowIntensity: 60, scale: 1 },
  },
  {
    id: 'caustics-kelp-forest',
    name: 'Kelp Forest Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Green-tinted caustics through kelp',
    defaultSettings: { speed: 40, intensity: 72, density: 55, color: '#4ade80', secondaryColor: '#bbf7d0', glowIntensity: 58, scale: 1 },
  },
  {
    id: 'caustics-rippling-sand',
    name: 'Rippling Sand Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Radiating caustics over rippled sand',
    defaultSettings: { speed: 52, intensity: 84, density: 50, color: '#a5f3fc', secondaryColor: '#ffffff', glowIntensity: 70, scale: 1 },
  },
  {
    id: 'caustics-wavy-surface',
    name: 'Wavy Surface Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Caustics from a wavy water surface',
    defaultSettings: { speed: 58, intensity: 80, density: 52, color: '#38bdf8', secondaryColor: '#e0f2fe', glowIntensity: 68, scale: 1 },
  },
  {
    id: 'caustics-magic-glow',
    name: 'Magic Glow Caustics',
    pack: 'caustics',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Glowing magical caustic light',
    defaultSettings: { speed: 50, intensity: 90, density: 50, color: '#22d3ee', secondaryColor: '#cffafe', glowIntensity: 85, scale: 1 },
  },

  // ===== RAIN EFFECTS PACK - rain sprite sheets (8x3, 24 frames) =====
  {
    id: 'rain-light-drizzle',
    name: 'Light Drizzle',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-drizzle',
    description: 'Fine, sparse droplets. Slow fall',
    defaultSettings: { speed: 35, intensity: 50, density: 30, color: '#dbeafe', secondaryColor: '#ffffff', glowIntensity: 30, scale: 1 },
  },
  {
    id: 'rain-steady',
    name: 'Steady Rain',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-rain',
    description: 'Consistent, even rainfall',
    defaultSettings: { speed: 55, intensity: 70, density: 55, color: '#dbeafe', secondaryColor: '#ffffff', glowIntensity: 35, scale: 1 },
  },
  {
    id: 'rain-heavy',
    name: 'Heavy Rain',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-rain',
    description: 'Thicker drops, heavier density',
    defaultSettings: { speed: 70, intensity: 85, density: 75, color: '#e0f2fe', secondaryColor: '#ffffff', glowIntensity: 40, scale: 1 },
  },
  {
    id: 'rain-torrential',
    name: 'Torrential Rain',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-rain',
    description: 'Extreme downpour. High impact',
    defaultSettings: { speed: 85, intensity: 95, density: 95, color: '#e0f2fe', secondaryColor: '#ffffff', glowIntensity: 50, scale: 1 },
  },
  {
    id: 'rain-wind-blown',
    name: 'Wind Blown Rain',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-rain-wind',
    description: 'Rain driven by strong wind',
    defaultSettings: { speed: 75, intensity: 75, density: 60, color: '#dbeafe', secondaryColor: '#ffffff', glowIntensity: 35, scale: 1 },
  },
  {
    id: 'rain-fine-mist',
    name: 'Fine Mist Rain',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-fog',
    description: 'Ultra-fine droplets and haze',
    defaultSettings: { speed: 30, intensity: 45, density: 40, color: '#eff6ff', secondaryColor: '#ffffff', glowIntensity: 30, scale: 1 },
  },
  {
    id: 'rain-sheet',
    name: 'Rain Sheet (Curtain)',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-rain',
    description: 'Vertical sheets of rain',
    defaultSettings: { speed: 65, intensity: 90, density: 85, color: '#e0f2fe', secondaryColor: '#ffffff', glowIntensity: 45, scale: 1 },
  },
  {
    id: 'rain-intermittent',
    name: 'Intermittent Rain',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-rain',
    description: 'Uneven rainfall with natural gaps',
    defaultSettings: { speed: 55, intensity: 65, density: 50, color: '#dbeafe', secondaryColor: '#ffffff', glowIntensity: 35, scale: 1 },
  },
  {
    id: 'rain-splatter-spray',
    name: 'Splatter Spray',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'droplets',
    description: 'Fine outward splashes and spray',
    defaultSettings: { speed: 60, intensity: 70, density: 55, color: '#e0f2fe', secondaryColor: '#ffffff', glowIntensity: 40, scale: 1 },
  },
  {
    id: 'rain-ground-mist',
    name: 'Ground Mist Rain',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-fog',
    description: 'Rain that creates rising ground mist',
    defaultSettings: { speed: 50, intensity: 65, density: 50, color: '#e0f2fe', secondaryColor: '#f1f5f9', glowIntensity: 40, scale: 1 },
  },
  {
    id: 'rain-micro-drizzle',
    name: 'Micro Drizzle',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-drizzle',
    description: 'Very small droplets and specks',
    defaultSettings: { speed: 30, intensity: 40, density: 25, color: '#eff6ff', secondaryColor: '#ffffff', glowIntensity: 25, scale: 1 },
  },
  {
    id: 'rain-sideways',
    name: 'Sideways Rain',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-rain-wind',
    description: 'Strong horizontal angle rain',
    defaultSettings: { speed: 80, intensity: 80, density: 65, color: '#dbeafe', secondaryColor: '#ffffff', glowIntensity: 35, scale: 1 },
  },
  {
    id: 'rain-fog-mix',
    name: 'Rain & Fog Mix',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-fog',
    description: 'Rain blended with diffuse fog',
    defaultSettings: { speed: 50, intensity: 70, density: 55, color: '#e0f2fe', secondaryColor: '#f1f5f9', glowIntensity: 40, scale: 1 },
  },
  {
    id: 'rain-droplet-impacts',
    name: 'Droplet Impacts',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'droplets',
    description: 'Droplets hitting surfaces',
    defaultSettings: { speed: 55, intensity: 75, density: 50, color: '#e0f2fe', secondaryColor: '#ffffff', glowIntensity: 45, scale: 1 },
  },
  {
    id: 'rain-dynamic-storm',
    name: 'Dynamic Storm Rain',
    pack: 'rain',
    renderMode: 'atmospheric',
    icon: 'cloud-lightning',
    description: 'Variable density, speed and size',
    defaultSettings: { speed: 85, intensity: 90, density: 80, color: '#e0f2fe', secondaryColor: '#ffffff', glowIntensity: 50, scale: 1 },
  },

  // ===== CEMETERY EFFECTS PACK - spooky sprite sheets (5x6, 30 frames) =====
  {
    id: 'cemetery-graveyard-fog',
    name: 'Graveyard Fog',
    pack: 'cemetery',
    renderMode: 'atmospheric',
    icon: 'cloud-fog',
    description: 'Low-lying drifting graveyard fog',
    defaultSettings: { speed: 25, intensity: 65, density: 60, color: '#cbd5e1', secondaryColor: '#f1f5f9', glowIntensity: 30, scale: 1 },
  },
  {
    id: 'cemetery-will-o-wisps',
    name: "Ghostly Will-o'-Wisps",
    pack: 'cemetery',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Flickering spirit fire orbs',
    defaultSettings: { speed: 45, intensity: 85, density: 40, color: '#2dd4bf', secondaryColor: '#99f6e4', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'cemetery-soul-spirits',
    name: 'Soul Spirits',
    pack: 'cemetery',
    renderMode: 'localized',
    icon: 'ghost',
    description: 'Drifting ghostly soul figures',
    defaultSettings: { speed: 35, intensity: 75, density: 40, color: '#5eead4', secondaryColor: '#ccfbf1', glowIntensity: 80, scale: 1 },
  },
  {
    id: 'cemetery-necrotic-aura',
    name: 'Necrotic Aura',
    pack: 'cemetery',
    renderMode: 'localized',
    icon: 'skull',
    description: 'Swirling dark decaying energy',
    defaultSettings: { speed: 45, intensity: 85, density: 60, color: '#7e22ce', secondaryColor: '#a855f7', glowIntensity: 80, scale: 1 },
  },
  {
    id: 'cemetery-blood-petals',
    name: 'Blood Petals',
    pack: 'cemetery',
    renderMode: 'atmospheric',
    icon: 'sparkles',
    description: 'Scattering crimson petals',
    defaultSettings: { speed: 40, intensity: 70, density: 50, color: '#dc2626', secondaryColor: '#ef4444', glowIntensity: 40, scale: 1 },
  },
  {
    id: 'cemetery-haunted-lantern',
    name: 'Haunted Lantern Light',
    pack: 'cemetery',
    renderMode: 'localized',
    icon: 'lamp',
    description: 'Eerie green lantern flame',
    defaultSettings: { speed: 40, intensity: 80, density: 40, color: '#4ade80', secondaryColor: '#bbf7d0', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'cemetery-cracked-stone-rise',
    name: 'Cracked Stone Rise',
    pack: 'cemetery',
    renderMode: 'terrain',
    icon: 'mountain',
    description: 'Tombstone rising from the ground',
    defaultSettings: { speed: 40, intensity: 70, density: 50, color: '#94a3b8', secondaryColor: '#cbd5e1', glowIntensity: 20, scale: 1 },
  },
  {
    id: 'cemetery-skeletal-remains',
    name: 'Skeletal Remains Shift',
    pack: 'cemetery',
    renderMode: 'terrain',
    icon: 'skull',
    description: 'Bones clattering and assembling',
    defaultSettings: { speed: 45, intensity: 70, density: 50, color: '#e7e5e4', secondaryColor: '#d6d3d1', glowIntensity: 20, scale: 1 },
  },
  {
    id: 'cemetery-dark-ritual-circle',
    name: 'Dark Ritual Circle',
    pack: 'cemetery',
    renderMode: 'localized',
    icon: 'circle-dot',
    description: 'Glowing red occult summoning circle',
    defaultSettings: { speed: 35, intensity: 90, density: 50, color: '#ef4444', secondaryColor: '#fca5a5', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'cemetery-coffin-burst',
    name: 'Coffin Burst',
    pack: 'cemetery',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Coffin bursting open with debris',
    defaultSettings: { speed: 55, intensity: 85, density: 55, color: '#a16207', secondaryColor: '#facc15', glowIntensity: 60, scale: 1 },
  },
  {
    id: 'cemetery-ethereal-mist-swirl',
    name: 'Ethereal Mist Swirl',
    pack: 'cemetery',
    renderMode: 'atmospheric',
    icon: 'cloud-fog',
    description: 'Spiraling spectral mist vortex',
    defaultSettings: { speed: 35, intensity: 65, density: 55, color: '#c4b5fd', secondaryColor: '#ede9fe', glowIntensity: 50, scale: 1 },
  },
  {
    id: 'cemetery-moonbeam-trees',
    name: 'Moonbeam Through Trees',
    pack: 'cemetery',
    renderMode: 'localized',
    icon: 'sun',
    description: 'Pale volumetric moonlight rays',
    defaultSettings: { speed: 25, intensity: 70, density: 40, color: '#bfdbfe', secondaryColor: '#eff6ff', glowIntensity: 70, scale: 1 },
  },
  {
    id: 'cemetery-draining-life-vortex',
    name: 'Draining Life Vortex',
    pack: 'cemetery',
    renderMode: 'localized',
    icon: 'circle-dot',
    description: 'Swirling green life-drain vortex',
    defaultSettings: { speed: 55, intensity: 90, density: 55, color: '#84cc16', secondaryColor: '#bef264', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'cemetery-candle-flame',
    name: 'Candle Flame Flicker',
    pack: 'cemetery',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Flickering candle flames',
    defaultSettings: { speed: 45, intensity: 75, density: 40, color: '#fcd34d', secondaryColor: '#fbbf24', glowIntensity: 70, scale: 1 },
  },
  {
    id: 'cemetery-bats-in-flight',
    name: 'Bats in Flight',
    pack: 'cemetery',
    renderMode: 'atmospheric',
    icon: 'ghost',
    description: 'Silhouetted bats flying past',
    defaultSettings: { speed: 60, intensity: 80, density: 50, color: '#1e293b', secondaryColor: '#475569', glowIntensity: 10, scale: 1 },
  },

  // ===== SUBTERRANEAN EFFECTS PACK - cave sprite sheets (5x6, 30 frames) =====
  {
    id: 'subterranean-cave-drips',
    name: 'Cave Drips',
    pack: 'subterranean',
    renderMode: 'localized',
    icon: 'droplets',
    description: 'Dripping water with ripple splashes',
    defaultSettings: { speed: 40, intensity: 75, density: 40, color: '#bae6fd', secondaryColor: '#e0f2fe', glowIntensity: 40, scale: 1 },
  },
  {
    id: 'subterranean-stalactite-seep',
    name: 'Stalactite Seep',
    pack: 'subterranean',
    renderMode: 'localized',
    icon: 'droplets',
    description: 'Water seeping down stalactites',
    defaultSettings: { speed: 30, intensity: 65, density: 40, color: '#a5f3fc', secondaryColor: '#cffafe', glowIntensity: 35, scale: 1 },
  },
  {
    id: 'subterranean-underground-stream',
    name: 'Underground Stream',
    pack: 'subterranean',
    renderMode: 'terrain',
    icon: 'waves',
    description: 'Flowing subterranean water',
    defaultSettings: { speed: 55, intensity: 75, density: 55, color: '#7dd3fc', secondaryColor: '#bae6fd', glowIntensity: 45, scale: 1 },
  },
  {
    id: 'subterranean-cave-mist',
    name: 'Cave Mist',
    pack: 'subterranean',
    renderMode: 'atmospheric',
    icon: 'cloud-fog',
    description: 'Drifting damp cave haze',
    defaultSettings: { speed: 25, intensity: 60, density: 60, color: '#e2e8f0', secondaryColor: '#f1f5f9', glowIntensity: 30, scale: 1 },
  },
  {
    id: 'subterranean-crystal-sparkles',
    name: 'Crystal Sparkles',
    pack: 'subterranean',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Twinkling crystal glints',
    defaultSettings: { speed: 45, intensity: 80, density: 45, color: '#bfdbfe', secondaryColor: '#ffffff', glowIntensity: 80, scale: 1 },
  },
  {
    id: 'subterranean-crystal-pulse',
    name: 'Crystal Pulse',
    pack: 'subterranean',
    renderMode: 'localized',
    icon: 'gem',
    description: 'Pulsing glowing crystal',
    defaultSettings: { speed: 40, intensity: 90, density: 45, color: '#c084fc', secondaryColor: '#e9d5ff', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'subterranean-bioluminescent-spores',
    name: 'Bioluminescent Spores',
    pack: 'subterranean',
    renderMode: 'atmospheric',
    icon: 'sparkle',
    description: 'Floating glowing spores',
    defaultSettings: { speed: 30, intensity: 75, density: 50, color: '#2dd4bf', secondaryColor: '#99f6e4', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'subterranean-glowing-mushroom-aura',
    name: 'Glowing Mushroom Aura',
    pack: 'subterranean',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Pulsing cave mushroom glow',
    defaultSettings: { speed: 35, intensity: 80, density: 45, color: '#22d3ee', secondaryColor: '#a5f3fc', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'subterranean-bat-swarm',
    name: 'Bat Swarm Silhouettes',
    pack: 'subterranean',
    renderMode: 'atmospheric',
    icon: 'ghost',
    description: 'Swarming bat silhouettes',
    defaultSettings: { speed: 65, intensity: 80, density: 55, color: '#1e293b', secondaryColor: '#475569', glowIntensity: 10, scale: 1 },
  },
  {
    id: 'subterranean-dustfall',
    name: 'Dustfall',
    pack: 'subterranean',
    renderMode: 'atmospheric',
    icon: 'sparkles',
    description: 'Falling glowing dust motes',
    defaultSettings: { speed: 35, intensity: 65, density: 55, color: '#fcd34d', secondaryColor: '#fde68a', glowIntensity: 55, scale: 1 },
  },
  {
    id: 'subterranean-pebble-collapse',
    name: 'Pebble Collapse',
    pack: 'subterranean',
    renderMode: 'terrain',
    icon: 'mountain',
    description: 'Tumbling falling pebbles',
    defaultSettings: { speed: 55, intensity: 70, density: 50, color: '#a8a29e', secondaryColor: '#d6d3d1', glowIntensity: 15, scale: 1 },
  },
  {
    id: 'subterranean-steam-vent',
    name: 'Steam Vent',
    pack: 'subterranean',
    renderMode: 'localized',
    icon: 'cloud',
    description: 'Rising billowing steam',
    defaultSettings: { speed: 45, intensity: 70, density: 55, color: '#f1f5f9', secondaryColor: '#ffffff', glowIntensity: 30, scale: 1 },
  },
  {
    id: 'subterranean-cave-fireflies',
    name: 'Cave Fireflies',
    pack: 'subterranean',
    renderMode: 'localized',
    icon: 'sparkle',
    description: 'Glowing drifting fireflies',
    defaultSettings: { speed: 45, intensity: 80, density: 40, color: '#fde047', secondaryColor: '#facc15', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'subterranean-arcane-cave-energy',
    name: 'Arcane Cave Energy',
    pack: 'subterranean',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Crackling arcane energy arcs',
    defaultSettings: { speed: 55, intensity: 90, density: 50, color: '#a855f7', secondaryColor: '#d8b4fe', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'subterranean-ambient',
    name: 'Subterranean Ambient',
    pack: 'subterranean',
    renderMode: 'atmospheric',
    icon: 'sparkles',
    description: 'Mixed ambient cave particles',
    defaultSettings: { speed: 30, intensity: 65, density: 55, color: '#93c5fd', secondaryColor: '#fde68a', glowIntensity: 60, scale: 1 },
  },

  // ===== MAGIC EFFECTS PACK - magic-circle sprite sheets (5x5, 25 frames) =====
  {
    id: 'magic-golden-arcane',
    name: 'Golden Arcane Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Rotating golden arcane summoning circle',
    defaultSettings: { speed: 45, intensity: 85, density: 50, color: '#f59e0b', secondaryColor: '#fcd34d', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'magic-cyan-heptagram',
    name: 'Cyan Heptagram',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Seven-pointed cyan magic circle',
    defaultSettings: { speed: 45, intensity: 85, density: 50, color: '#22d3ee', secondaryColor: '#a5f3fc', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'magic-purple-hexagram',
    name: 'Purple Hexagram',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Six-pointed violet magic circle',
    defaultSettings: { speed: 45, intensity: 85, density: 50, color: '#a855f7', secondaryColor: '#d8b4fe', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'magic-verdant-summoning',
    name: 'Verdant Summoning Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Swirling green summoning circle',
    defaultSettings: { speed: 45, intensity: 85, density: 50, color: '#22c55e', secondaryColor: '#86efac', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'magic-infernal-flame',
    name: 'Infernal Flame Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Burning fiery summoning circle',
    defaultSettings: { speed: 50, intensity: 90, density: 50, color: '#f97316', secondaryColor: '#fca5a5', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'magic-radiant-ward',
    name: 'Radiant Ward Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Bright holy ward magic circle',
    defaultSettings: { speed: 40, intensity: 85, density: 50, color: '#f8fafc', secondaryColor: '#e2e8f0', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'magic-magenta-hex',
    name: 'Magenta Hex Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Sparkling magenta magic circle',
    defaultSettings: { speed: 45, intensity: 85, density: 50, color: '#d946ef', secondaryColor: '#f0abfc', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'magic-golden-rune',
    name: 'Golden Rune Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Glowing golden rune-dot circle',
    defaultSettings: { speed: 45, intensity: 85, density: 50, color: '#fde047', secondaryColor: '#fef08a', glowIntensity: 88, scale: 1 },
  },
  {
    id: 'magic-azure-conjuration',
    name: 'Azure Conjuration Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Flowing azure conjuration circle',
    defaultSettings: { speed: 45, intensity: 85, density: 50, color: '#3b82f6', secondaryColor: '#93c5fd', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'magic-violet-enchantment',
    name: 'Violet Enchantment Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Crackling violet enchantment circle',
    defaultSettings: { speed: 45, intensity: 85, density: 50, color: '#8b5cf6', secondaryColor: '#c4b5fd', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'magic-emerald-nature',
    name: 'Emerald Nature Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Light-green nature magic circle',
    defaultSettings: { speed: 40, intensity: 80, density: 50, color: '#4ade80', secondaryColor: '#bbf7d0', glowIntensity: 82, scale: 1 },
  },
  {
    id: 'magic-spiral-vortex',
    name: 'Spiral Vortex Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'circle-dot',
    description: 'Swirling magical spiral vortex',
    defaultSettings: { speed: 55, intensity: 85, density: 50, color: '#f1f5f9', secondaryColor: '#86efac', glowIntensity: 80, scale: 1 },
  },
  {
    id: 'magic-crimson-pentagram',
    name: 'Crimson Pentagram',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Ominous red pentagram circle',
    defaultSettings: { speed: 45, intensity: 88, density: 50, color: '#dc2626', secondaryColor: '#fca5a5', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'magic-amber-alchemy',
    name: 'Amber Alchemy Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Geometric amber alchemy circle',
    defaultSettings: { speed: 45, intensity: 85, density: 50, color: '#f59e0b', secondaryColor: '#fbbf24', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'magic-frost-sigil',
    name: 'Frost Sigil Circle',
    pack: 'magic',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Crystalline icy frost magic circle',
    defaultSettings: { speed: 40, intensity: 85, density: 50, color: '#38bdf8', secondaryColor: '#bae6fd', glowIntensity: 88, scale: 1 },
  },

  // ===== LIGHT SOURCE EFFECTS PACK - illumination sprite sheets (5x6, 30 frames) =====
  {
    id: 'lightsource-wall-torch',
    name: 'Wall Torch',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Flickering wall-mounted torch',
    defaultSettings: { speed: 50, intensity: 85, density: 40, color: '#f59e0b', secondaryColor: '#fbbf24', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'lightsource-ornate-lantern',
    name: 'Ornate Lantern',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'lamp',
    description: 'Decorative glowing lantern',
    defaultSettings: { speed: 40, intensity: 80, density: 40, color: '#f59e0b', secondaryColor: '#fcd34d', glowIntensity: 80, scale: 1 },
  },
  {
    id: 'lightsource-iron-lantern',
    name: 'Iron Lantern',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'lamp',
    description: 'Simple iron-framed lantern',
    defaultSettings: { speed: 40, intensity: 75, density: 40, color: '#f59e0b', secondaryColor: '#fcd34d', glowIntensity: 75, scale: 1 },
  },
  {
    id: 'lightsource-hanging-lantern',
    name: 'Hanging Lantern',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'lamp',
    description: 'Swaying suspended lantern',
    defaultSettings: { speed: 40, intensity: 80, density: 40, color: '#f59e0b', secondaryColor: '#fcd34d', glowIntensity: 80, scale: 1 },
  },
  {
    id: 'lightsource-carriage-lantern',
    name: 'Carriage Lantern',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'lamp',
    description: 'Tall bright carriage lantern',
    defaultSettings: { speed: 45, intensity: 85, density: 40, color: '#f59e0b', secondaryColor: '#fcd34d', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'lightsource-campfire',
    name: 'Campfire',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Crackling log campfire',
    defaultSettings: { speed: 55, intensity: 88, density: 50, color: '#f97316', secondaryColor: '#fbbf24', glowIntensity: 88, scale: 1 },
  },
  {
    id: 'lightsource-sparkler-burst',
    name: 'Sparkler Burst',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Radiating spark burst',
    defaultSettings: { speed: 60, intensity: 85, density: 55, color: '#fbbf24', secondaryColor: '#fde68a', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'lightsource-candle',
    name: 'Candle',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Single flickering candle',
    defaultSettings: { speed: 45, intensity: 70, density: 35, color: '#f59e0b', secondaryColor: '#fef08a', glowIntensity: 75, scale: 1 },
  },
  {
    id: 'lightsource-glowing-orb',
    name: 'Glowing Orb',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'sparkle',
    description: 'Pulsing orb of warm light',
    defaultSettings: { speed: 35, intensity: 85, density: 40, color: '#facc15', secondaryColor: '#fde68a', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'lightsource-fire-brazier',
    name: 'Fire Brazier',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Flaming metal fire bowl',
    defaultSettings: { speed: 55, intensity: 88, density: 50, color: '#f97316', secondaryColor: '#fca5a5', glowIntensity: 88, scale: 1 },
  },
  {
    id: 'lightsource-rune-light-circle',
    name: 'Rune Light Circle',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Glowing runic light ring',
    defaultSettings: { speed: 40, intensity: 82, density: 40, color: '#fde047', secondaryColor: '#fef08a', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'lightsource-pendant-light',
    name: 'Pendant Light',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'lamp',
    description: 'Hanging swaying light orb',
    defaultSettings: { speed: 40, intensity: 82, density: 40, color: '#facc15', secondaryColor: '#fde68a', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'lightsource-radiant-starburst',
    name: 'Radiant Starburst',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Bright twinkling star burst',
    defaultSettings: { speed: 45, intensity: 88, density: 45, color: '#fde047', secondaryColor: '#fffbeb', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'lightsource-soft-star-glow',
    name: 'Soft Star Glow',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'sparkle',
    description: 'Diffuse soft glowing star',
    defaultSettings: { speed: 35, intensity: 75, density: 40, color: '#fde68a', secondaryColor: '#fef9c3', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'lightsource-sparkle-starburst',
    name: 'Sparkle Starburst',
    pack: 'lightsource',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Glittering sparkle star burst',
    defaultSettings: { speed: 50, intensity: 85, density: 50, color: '#fbbf24', secondaryColor: '#fde68a', glowIntensity: 88, scale: 1 },
  },
  // ----- Light Source Revised Effects Pack (15) -----
  {
    id: 'lsr-torch',
    name: 'Torch',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Flickering wall torch flame',
    defaultSettings: { speed: 50, intensity: 80, density: 50, color: '#f97316', secondaryColor: '#fbbf24', glowIntensity: 80, scale: 1 },
  },
  {
    id: 'lsr-fire-glow',
    name: 'Fire Glow',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Soft glowing fire light',
    defaultSettings: { speed: 45, intensity: 78, density: 50, color: '#fb923c', secondaryColor: '#fde68a', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'lsr-fire-bowl',
    name: 'Fire Bowl',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Burning fire bowl',
    defaultSettings: { speed: 48, intensity: 82, density: 50, color: '#f97316', secondaryColor: '#fbbf24', glowIntensity: 80, scale: 1 },
  },
  {
    id: 'lsr-carriage-lantern',
    name: 'Carriage Lantern',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'lamp',
    description: 'Ornate carriage lantern light',
    defaultSettings: { speed: 35, intensity: 70, density: 40, color: '#fbbf24', secondaryColor: '#fde68a', glowIntensity: 78, scale: 1 },
  },
  {
    id: 'lsr-hanging-lantern',
    name: 'Hanging Lantern',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'lamp',
    description: 'Glowing hanging lantern',
    defaultSettings: { speed: 35, intensity: 70, density: 40, color: '#fbbf24', secondaryColor: '#fde68a', glowIntensity: 78, scale: 1 },
  },
  {
    id: 'lsr-candle',
    name: 'Candle',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Flickering candle flame',
    defaultSettings: { speed: 40, intensity: 65, density: 40, color: '#fde68a', secondaryColor: '#fef9c3', glowIntensity: 72, scale: 1 },
  },
  {
    id: 'lsr-glowing-orb',
    name: 'Glowing Orb',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Pulsing glowing orb of light',
    defaultSettings: { speed: 40, intensity: 80, density: 50, color: '#fbbf24', secondaryColor: '#fef3c7', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'lsr-campfire',
    name: 'Campfire',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Crackling campfire',
    defaultSettings: { speed: 50, intensity: 85, density: 55, color: '#f97316', secondaryColor: '#fbbf24', glowIntensity: 82, scale: 1 },
  },
  {
    id: 'lsr-sparkles',
    name: 'Sparkles',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Drifting ember sparkles',
    defaultSettings: { speed: 55, intensity: 75, density: 60, color: '#fbbf24', secondaryColor: '#fde68a', glowIntensity: 80, scale: 1 },
  },
  {
    id: 'lsr-fire-brazier',
    name: 'Fire Brazier',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Blazing fire brazier',
    defaultSettings: { speed: 50, intensity: 85, density: 55, color: '#f97316', secondaryColor: '#fbbf24', glowIntensity: 82, scale: 1 },
  },
  {
    id: 'lsr-blue-flame',
    name: 'Blue Flame',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Ethereal blue flame',
    defaultSettings: { speed: 50, intensity: 80, density: 50, color: '#38bdf8', secondaryColor: '#bae6fd', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'lsr-green-flame',
    name: 'Green Flame',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'flame',
    description: 'Eerie green flame',
    defaultSettings: { speed: 50, intensity: 80, density: 50, color: '#4ade80', secondaryColor: '#bbf7d0', glowIntensity: 85, scale: 1 },
  },
  {
    id: 'lsr-starburst',
    name: 'Starburst',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Radiant twinkling starburst',
    defaultSettings: { speed: 50, intensity: 88, density: 50, color: '#fde68a', secondaryColor: '#fef9c3', glowIntensity: 90, scale: 1 },
  },
  {
    id: 'lsr-arcane-circle',
    name: 'Arcane Circle',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Rotating arcane rune circle',
    defaultSettings: { speed: 40, intensity: 80, density: 50, color: '#a855f7', secondaryColor: '#d8b4fe', glowIntensity: 88, scale: 1 },
  },
  {
    id: 'lsr-smoke',
    name: 'Smoke',
    pack: 'lightsource-revised',
    renderMode: 'localized',
    icon: 'cloud',
    description: 'Rising plume of smoke',
    defaultSettings: { speed: 35, intensity: 60, density: 50, color: '#9ca3af', secondaryColor: '#d1d5db', glowIntensity: 30, scale: 1 },
  },
  {
    id: 'new-fire-torch',
    name: 'Fire Torch',
    pack: 'new',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Fire Torch sprite animation',
    defaultSettings: { speed: 50, intensity: 80, density: 50, color: '#ff6600', glowIntensity: 60, scale: 1 },
  },
  {
    id: 'new-smoke',
    name: 'Smoke',
    pack: 'new',
    renderMode: 'localized',
    icon: 'sparkles',
    description: 'Smoke sprite animation',
    defaultSettings: { speed: 50, intensity: 80, density: 50, color: '#9ca3af', glowIntensity: 60, scale: 1 },
  },
  // NEW_EFFECT_DEFS
]

// Helper functions
export function getEffectsByPack(pack: EffectPack): EffectDefinition[] {
  return effectsLibrary.filter(e => e.pack === pack)
}

export function getEffectById(id: string): EffectDefinition | undefined {
  return effectsLibrary.find(e => e.id === id)
}

export function getEffectsByRenderMode(mode: RenderMode): EffectDefinition[] {
  return effectsLibrary.filter(e => e.renderMode === mode)
}

export function getAllEffects(): EffectDefinition[] {
  return effectsLibrary
}

// Backwards compatibility exports
export type EffectCategory = EffectPack
export type UnifiedEffectSettings = EffectSettings
export type BaseEffectComponent = EffectId
export type PerformanceLevel = 'low' | 'medium' | 'high'
export type GenreTag = 'fantasy' | 'scifi' | 'natural'
export type EffectTypeTag = 'weather' | 'light' | 'magic' | 'ambient'
export type ExpandedEffectDefinition = EffectDefinition
export const categoryMeta = EFFECT_PACKS
